// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goods.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createGood = `-- name: CreateGood :one
INSERT INTO goods (name, weight, height, length, width, quantity_available)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, weight, height, length, width, quantity_available
`

type CreateGoodParams struct {
	Name              string  `json:"name"`
	Weight            float64 `json:"weight"`
	Height            float64 `json:"height"`
	Length            float64 `json:"length"`
	Width             float64 `json:"width"`
	QuantityAvailable int32   `json:"quantity_available"`
}

func (q *Queries) CreateGood(ctx context.Context, arg CreateGoodParams) (Good, error) {
	row := q.db.QueryRow(ctx, createGood,
		arg.Name,
		arg.Weight,
		arg.Height,
		arg.Length,
		arg.Width,
		arg.QuantityAvailable,
	)
	var i Good
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.QuantityAvailable,
	)
	return i, err
}

const deleteGood = `-- name: DeleteGood :exec
DELETE FROM goods
WHERE id = $1
`

func (q *Queries) DeleteGood(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGood, id)
	return err
}

const getGoodByID = `-- name: GetGoodByID :one
SELECT id, name, weight, height, length, width, quantity_available FROM goods
WHERE id = $1
`

func (q *Queries) GetGoodByID(ctx context.Context, id uuid.UUID) (Good, error) {
	row := q.db.QueryRow(ctx, getGoodByID, id)
	var i Good
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.QuantityAvailable,
	)
	return i, err
}

const listAvailableGoods = `-- name: ListAvailableGoods :many
SELECT id, name, weight, height, length, width, quantity_available FROM goods
WHERE quantity_available > 0
ORDER BY name
`

func (q *Queries) ListAvailableGoods(ctx context.Context) ([]Good, error) {
	rows, err := q.db.Query(ctx, listAvailableGoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Good
	for rows.Next() {
		var i Good
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Weight,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.QuantityAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoods = `-- name: ListGoods :many
SELECT id, name, weight, height, length, width, quantity_available FROM goods
ORDER BY id
`

func (q *Queries) ListGoods(ctx context.Context) ([]Good, error) {
	rows, err := q.db.Query(ctx, listGoods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Good
	for rows.Next() {
		var i Good
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Weight,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.QuantityAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGood = `-- name: UpdateGood :one
UPDATE goods
SET name = $2, weight = $3, height = $4, length = $5, width = $6
WHERE id = $1
RETURNING id, name, weight, height, length, width, quantity_available
`

type UpdateGoodParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Weight float64   `json:"weight"`
	Height float64   `json:"height"`
	Length float64   `json:"length"`
	Width  float64   `json:"width"`
}

func (q *Queries) UpdateGood(ctx context.Context, arg UpdateGoodParams) (Good, error) {
	row := q.db.QueryRow(ctx, updateGood,
		arg.ID,
		arg.Name,
		arg.Weight,
		arg.Height,
		arg.Length,
		arg.Width,
	)
	var i Good
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.QuantityAvailable,
	)
	return i, err
}

const updateGoodQuantity = `-- name: UpdateGoodQuantity :one
UPDATE goods
SET quantity_available = quantity_available + $2
WHERE id = $1
RETURNING id, name, weight, height, length, width, quantity_available
`

type UpdateGoodQuantityParams struct {
	ID                uuid.UUID `json:"id"`
	QuantityAvailable int32     `json:"quantity_available"`
}

func (q *Queries) UpdateGoodQuantity(ctx context.Context, arg UpdateGoodQuantityParams) (Good, error) {
	row := q.db.QueryRow(ctx, updateGoodQuantity, arg.ID, arg.QuantityAvailable)
	var i Good
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Weight,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.QuantityAvailable,
	)
	return i, err
}
