// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: internal_locker_cells.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createInternalLockerCell = `-- name: CreateInternalLockerCell :one
INSERT INTO locker_cells_internal (post_id, height, length, width, status, cell_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, post_id, height, length, width, status, cell_number
`

type CreateInternalLockerCellParams struct {
	PostID     uuid.UUID `json:"post_id"`
	Height     float64   `json:"height"`
	Length     float64   `json:"length"`
	Width      float64   `json:"width"`
	Status     string    `json:"status"`
	CellNumber *int32    `json:"cell_number"`
}

func (q *Queries) CreateInternalLockerCell(ctx context.Context, arg CreateInternalLockerCellParams) (LockerCellsInternal, error) {
	row := q.db.QueryRow(ctx, createInternalLockerCell,
		arg.PostID,
		arg.Height,
		arg.Length,
		arg.Width,
		arg.Status,
		arg.CellNumber,
	)
	var i LockerCellsInternal
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const deleteInternalLockerCell = `-- name: DeleteInternalLockerCell :exec
DELETE FROM locker_cells_internal
WHERE id = $1
`

func (q *Queries) DeleteInternalLockerCell(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInternalLockerCell, id)
	return err
}

const findAvailableInternalCell = `-- name: FindAvailableInternalCell :one
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_internal
WHERE status = 'available'
  AND height >= $1
  AND length >= $2
  AND width >= $3
ORDER BY (height * length * width)
LIMIT 1
`

type FindAvailableInternalCellParams struct {
	Height float64 `json:"height"`
	Length float64 `json:"length"`
	Width  float64 `json:"width"`
}

func (q *Queries) FindAvailableInternalCell(ctx context.Context, arg FindAvailableInternalCellParams) (LockerCellsInternal, error) {
	row := q.db.QueryRow(ctx, findAvailableInternalCell, arg.Height, arg.Length, arg.Width)
	var i LockerCellsInternal
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const getInternalLockerCellByID = `-- name: GetInternalLockerCellByID :one
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_internal
WHERE id = $1
`

func (q *Queries) GetInternalLockerCellByID(ctx context.Context, id uuid.UUID) (LockerCellsInternal, error) {
	row := q.db.QueryRow(ctx, getInternalLockerCellByID, id)
	var i LockerCellsInternal
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const listInternalLockerCells = `-- name: ListInternalLockerCells :many
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_internal
ORDER BY id
`

func (q *Queries) ListInternalLockerCells(ctx context.Context) ([]LockerCellsInternal, error) {
	rows, err := q.db.Query(ctx, listInternalLockerCells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockerCellsInternal
	for rows.Next() {
		var i LockerCellsInternal
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.Status,
			&i.CellNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInternalLockerCellsByPostID = `-- name: ListInternalLockerCellsByPostID :many
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_internal
WHERE post_id = $1
ORDER BY cell_number
`

func (q *Queries) ListInternalLockerCellsByPostID(ctx context.Context, postID uuid.UUID) ([]LockerCellsInternal, error) {
	rows, err := q.db.Query(ctx, listInternalLockerCellsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockerCellsInternal
	for rows.Next() {
		var i LockerCellsInternal
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.Status,
			&i.CellNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInternalLockerCellDimensions = `-- name: UpdateInternalLockerCellDimensions :one
UPDATE locker_cells_internal
SET height = $2, length = $3, width = $4
WHERE id = $1
RETURNING id, post_id, height, length, width, status, cell_number
`

type UpdateInternalLockerCellDimensionsParams struct {
	ID     uuid.UUID `json:"id"`
	Height float64   `json:"height"`
	Length float64   `json:"length"`
	Width  float64   `json:"width"`
}

func (q *Queries) UpdateInternalLockerCellDimensions(ctx context.Context, arg UpdateInternalLockerCellDimensionsParams) (LockerCellsInternal, error) {
	row := q.db.QueryRow(ctx, updateInternalLockerCellDimensions,
		arg.ID,
		arg.Height,
		arg.Length,
		arg.Width,
	)
	var i LockerCellsInternal
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const updateInternalLockerCellStatus = `-- name: UpdateInternalLockerCellStatus :one
UPDATE locker_cells_internal
SET status = $2
WHERE id = $1
RETURNING id, post_id, height, length, width, status, cell_number
`

type UpdateInternalLockerCellStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateInternalLockerCellStatus(ctx context.Context, arg UpdateInternalLockerCellStatusParams) (LockerCellsInternal, error) {
	row := q.db.QueryRow(ctx, updateInternalLockerCellStatus, arg.ID, arg.Status)
	var i LockerCellsInternal
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}
