// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locker_cells.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createLockerCell = `-- name: CreateLockerCell :one
INSERT INTO locker_cells_out (post_id, height, length, width, status, cell_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, post_id, height, length, width, status, cell_number
`

type CreateLockerCellParams struct {
	PostID     uuid.UUID `json:"post_id"`
	Height     float64   `json:"height"`
	Length     float64   `json:"length"`
	Width      float64   `json:"width"`
	Status     string    `json:"status"`
	CellNumber *int32    `json:"cell_number"`
}

func (q *Queries) CreateLockerCell(ctx context.Context, arg CreateLockerCellParams) (LockerCellsOut, error) {
	row := q.db.QueryRow(ctx, createLockerCell,
		arg.PostID,
		arg.Height,
		arg.Length,
		arg.Width,
		arg.Status,
		arg.CellNumber,
	)
	var i LockerCellsOut
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const deleteLockerCell = `-- name: DeleteLockerCell :exec
DELETE FROM locker_cells_out
WHERE id = $1
`

func (q *Queries) DeleteLockerCell(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLockerCell, id)
	return err
}

const findAvailableCell = `-- name: FindAvailableCell :one
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_out
WHERE status = 'available'
  AND height >= $1
  AND length >= $2
  AND width >= $3
ORDER BY (height * length * width)
LIMIT 1
`

type FindAvailableCellParams struct {
	Height float64 `json:"height"`
	Length float64 `json:"length"`
	Width  float64 `json:"width"`
}

func (q *Queries) FindAvailableCell(ctx context.Context, arg FindAvailableCellParams) (LockerCellsOut, error) {
	row := q.db.QueryRow(ctx, findAvailableCell, arg.Height, arg.Length, arg.Width)
	var i LockerCellsOut
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const getLockerCellByID = `-- name: GetLockerCellByID :one
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_out
WHERE id = $1
`

func (q *Queries) GetLockerCellByID(ctx context.Context, id uuid.UUID) (LockerCellsOut, error) {
	row := q.db.QueryRow(ctx, getLockerCellByID, id)
	var i LockerCellsOut
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const listLockerCells = `-- name: ListLockerCells :many
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_out
ORDER BY id
`

func (q *Queries) ListLockerCells(ctx context.Context) ([]LockerCellsOut, error) {
	rows, err := q.db.Query(ctx, listLockerCells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockerCellsOut
	for rows.Next() {
		var i LockerCellsOut
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.Status,
			&i.CellNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockerCellsByPostID = `-- name: ListLockerCellsByPostID :many
SELECT id, post_id, height, length, width, status, cell_number FROM locker_cells_out
WHERE post_id = $1
ORDER BY cell_number
`

func (q *Queries) ListLockerCellsByPostID(ctx context.Context, postID uuid.UUID) ([]LockerCellsOut, error) {
	rows, err := q.db.Query(ctx, listLockerCellsByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockerCellsOut
	for rows.Next() {
		var i LockerCellsOut
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.Height,
			&i.Length,
			&i.Width,
			&i.Status,
			&i.CellNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLockerCellDimensions = `-- name: UpdateLockerCellDimensions :one
UPDATE locker_cells_out
SET height = $2, length = $3, width = $4
WHERE id = $1
RETURNING id, post_id, height, length, width, status, cell_number
`

type UpdateLockerCellDimensionsParams struct {
	ID     uuid.UUID `json:"id"`
	Height float64   `json:"height"`
	Length float64   `json:"length"`
	Width  float64   `json:"width"`
}

func (q *Queries) UpdateLockerCellDimensions(ctx context.Context, arg UpdateLockerCellDimensionsParams) (LockerCellsOut, error) {
	row := q.db.QueryRow(ctx, updateLockerCellDimensions,
		arg.ID,
		arg.Height,
		arg.Length,
		arg.Width,
	)
	var i LockerCellsOut
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}

const updateLockerCellStatus = `-- name: UpdateLockerCellStatus :one
UPDATE locker_cells_out
SET status = $2
WHERE id = $1
RETURNING id, post_id, height, length, width, status, cell_number
`

type UpdateLockerCellStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateLockerCellStatus(ctx context.Context, arg UpdateLockerCellStatusParams) (LockerCellsOut, error) {
	row := q.db.QueryRow(ctx, updateLockerCellStatus, arg.ID, arg.Status)
	var i LockerCellsOut
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.Height,
		&i.Length,
		&i.Width,
		&i.Status,
		&i.CellNumber,
	)
	return i, err
}
