// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockArduinoInterface creates a new instance of MockArduinoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArduinoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArduinoInterface {
	mock := &MockArduinoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockArduinoInterface is an autogenerated mock type for the ArduinoInterface type
type MockArduinoInterface struct {
	mock.Mock
}

type MockArduinoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArduinoInterface) EXPECT() *MockArduinoInterface_Expecter {
	return &MockArduinoInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockArduinoInterface
func (_mock *MockArduinoInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArduinoInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockArduinoInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockArduinoInterface_Expecter) Close() *MockArduinoInterface_Close_Call {
	return &MockArduinoInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockArduinoInterface_Close_Call) Run(run func()) *MockArduinoInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArduinoInterface_Close_Call) Return(err error) *MockArduinoInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArduinoInterface_Close_Call) RunAndReturn(run func() error) *MockArduinoInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetCellsCount provides a mock function for the type MockArduinoInterface
func (_mock *MockArduinoInterface) GetCellsCount() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCellsCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockArduinoInterface_GetCellsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellsCount'
type MockArduinoInterface_GetCellsCount_Call struct {
	*mock.Call
}

// GetCellsCount is a helper method to define mock.On call
func (_e *MockArduinoInterface_Expecter) GetCellsCount() *MockArduinoInterface_GetCellsCount_Call {
	return &MockArduinoInterface_GetCellsCount_Call{Call: _e.mock.On("GetCellsCount")}
}

func (_c *MockArduinoInterface_GetCellsCount_Call) Run(run func()) *MockArduinoInterface_GetCellsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArduinoInterface_GetCellsCount_Call) Return(n int, err error) *MockArduinoInterface_GetCellsCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockArduinoInterface_GetCellsCount_Call) RunAndReturn(run func() (int, error)) *MockArduinoInterface_GetCellsCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsMockMode provides a mock function for the type MockArduinoInterface
func (_mock *MockArduinoInterface) IsMockMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsMockMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockArduinoInterface_IsMockMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMockMode'
type MockArduinoInterface_IsMockMode_Call struct {
	*mock.Call
}

// IsMockMode is a helper method to define mock.On call
func (_e *MockArduinoInterface_Expecter) IsMockMode() *MockArduinoInterface_IsMockMode_Call {
	return &MockArduinoInterface_IsMockMode_Call{Call: _e.mock.On("IsMockMode")}
}

func (_c *MockArduinoInterface_IsMockMode_Call) Run(run func()) *MockArduinoInterface_IsMockMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArduinoInterface_IsMockMode_Call) Return(b bool) *MockArduinoInterface_IsMockMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockArduinoInterface_IsMockMode_Call) RunAndReturn(run func() bool) *MockArduinoInterface_IsMockMode_Call {
	_c.Call.Return(run)
	return _c
}

// OpenCell provides a mock function for the type MockArduinoInterface
func (_mock *MockArduinoInterface) OpenCell(cellNumber int) error {
	ret := _mock.Called(cellNumber)

	if len(ret) == 0 {
		panic("no return value specified for OpenCell")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(cellNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArduinoInterface_OpenCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenCell'
type MockArduinoInterface_OpenCell_Call struct {
	*mock.Call
}

// OpenCell is a helper method to define mock.On call
//   - cellNumber int
func (_e *MockArduinoInterface_Expecter) OpenCell(cellNumber interface{}) *MockArduinoInterface_OpenCell_Call {
	return &MockArduinoInterface_OpenCell_Call{Call: _e.mock.On("OpenCell", cellNumber)}
}

func (_c *MockArduinoInterface_OpenCell_Call) Run(run func(cellNumber int)) *MockArduinoInterface_OpenCell_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArduinoInterface_OpenCell_Call) Return(err error) *MockArduinoInterface_OpenCell_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArduinoInterface_OpenCell_Call) RunAndReturn(run func(cellNumber int) error) *MockArduinoInterface_OpenCell_Call {
	_c.Call.Return(run)
	return _c
}

// OpenInternalDoor provides a mock function for the type MockArduinoInterface
func (_mock *MockArduinoInterface) OpenInternalDoor(doorNumber int) error {
	ret := _mock.Called(doorNumber)

	if len(ret) == 0 {
		panic("no return value specified for OpenInternalDoor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(doorNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockArduinoInterface_OpenInternalDoor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenInternalDoor'
type MockArduinoInterface_OpenInternalDoor_Call struct {
	*mock.Call
}

// OpenInternalDoor is a helper method to define mock.On call
//   - doorNumber int
func (_e *MockArduinoInterface_Expecter) OpenInternalDoor(doorNumber interface{}) *MockArduinoInterface_OpenInternalDoor_Call {
	return &MockArduinoInterface_OpenInternalDoor_Call{Call: _e.mock.On("OpenInternalDoor", doorNumber)}
}

func (_c *MockArduinoInterface_OpenInternalDoor_Call) Run(run func(doorNumber int)) *MockArduinoInterface_OpenInternalDoor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockArduinoInterface_OpenInternalDoor_Call) Return(err error) *MockArduinoInterface_OpenInternalDoor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockArduinoInterface_OpenInternalDoor_Call) RunAndReturn(run func(doorNumber int) error) *MockArduinoInterface_OpenInternalDoor_Call {
	_c.Call.Return(run)
	return _c
}
