// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/locker-agent/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCellMappingInterface creates a new instance of MockCellMappingInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCellMappingInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCellMappingInterface {
	mock := &MockCellMappingInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCellMappingInterface is an autogenerated mock type for the CellMappingInterface type
type MockCellMappingInterface struct {
	mock.Mock
}

type MockCellMappingInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCellMappingInterface) EXPECT() *MockCellMappingInterface_Expecter {
	return &MockCellMappingInterface_Expecter{mock: &_m.Mock}
}

// GetCellNumber provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) GetCellNumber(cellUUID uuid.UUID) (int, entity.CellType, error) {
	ret := _mock.Called(cellUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCellNumber")
	}

	var r0 int
	var r1 entity.CellType
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (int, entity.CellType, error)); ok {
		return returnFunc(cellUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) int); ok {
		r0 = returnFunc(cellUUID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) entity.CellType); ok {
		r1 = returnFunc(cellUUID)
	} else {
		r1 = ret.Get(1).(entity.CellType)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID) error); ok {
		r2 = returnFunc(cellUUID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCellMappingInterface_GetCellNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellNumber'
type MockCellMappingInterface_GetCellNumber_Call struct {
	*mock.Call
}

// GetCellNumber is a helper method to define mock.On call
//   - cellUUID uuid.UUID
func (_e *MockCellMappingInterface_Expecter) GetCellNumber(cellUUID interface{}) *MockCellMappingInterface_GetCellNumber_Call {
	return &MockCellMappingInterface_GetCellNumber_Call{Call: _e.mock.On("GetCellNumber", cellUUID)}
}

func (_c *MockCellMappingInterface_GetCellNumber_Call) Run(run func(cellUUID uuid.UUID)) *MockCellMappingInterface_GetCellNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCellMappingInterface_GetCellNumber_Call) Return(n int, cellType entity.CellType, err error) *MockCellMappingInterface_GetCellNumber_Call {
	_c.Call.Return(n, cellType, err)
	return _c
}

func (_c *MockCellMappingInterface_GetCellNumber_Call) RunAndReturn(run func(cellUUID uuid.UUID) (int, entity.CellType, error)) *MockCellMappingInterface_GetCellNumber_Call {
	_c.Call.Return(run)
	return _c
}

// GetCellUUID provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) GetCellUUID(cellNumber int) (uuid.UUID, error) {
	ret := _mock.Called(cellNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetCellUUID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (uuid.UUID, error)); ok {
		return returnFunc(cellNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(int) uuid.UUID); ok {
		r0 = returnFunc(cellNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(cellNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCellMappingInterface_GetCellUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellUUID'
type MockCellMappingInterface_GetCellUUID_Call struct {
	*mock.Call
}

// GetCellUUID is a helper method to define mock.On call
//   - cellNumber int
func (_e *MockCellMappingInterface_Expecter) GetCellUUID(cellNumber interface{}) *MockCellMappingInterface_GetCellUUID_Call {
	return &MockCellMappingInterface_GetCellUUID_Call{Call: _e.mock.On("GetCellUUID", cellNumber)}
}

func (_c *MockCellMappingInterface_GetCellUUID_Call) Run(run func(cellNumber int)) *MockCellMappingInterface_GetCellUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCellMappingInterface_GetCellUUID_Call) Return(uUID uuid.UUID, err error) *MockCellMappingInterface_GetCellUUID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockCellMappingInterface_GetCellUUID_Call) RunAndReturn(run func(cellNumber int) (uuid.UUID, error)) *MockCellMappingInterface_GetCellUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetInternalCellUUID provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) GetInternalCellUUID(doorNumber int) (uuid.UUID, error) {
	ret := _mock.Called(doorNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetInternalCellUUID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (uuid.UUID, error)); ok {
		return returnFunc(doorNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(int) uuid.UUID); ok {
		r0 = returnFunc(doorNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(doorNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCellMappingInterface_GetInternalCellUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInternalCellUUID'
type MockCellMappingInterface_GetInternalCellUUID_Call struct {
	*mock.Call
}

// GetInternalCellUUID is a helper method to define mock.On call
//   - doorNumber int
func (_e *MockCellMappingInterface_Expecter) GetInternalCellUUID(doorNumber interface{}) *MockCellMappingInterface_GetInternalCellUUID_Call {
	return &MockCellMappingInterface_GetInternalCellUUID_Call{Call: _e.mock.On("GetInternalCellUUID", doorNumber)}
}

func (_c *MockCellMappingInterface_GetInternalCellUUID_Call) Run(run func(doorNumber int)) *MockCellMappingInterface_GetInternalCellUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCellMappingInterface_GetInternalCellUUID_Call) Return(uUID uuid.UUID, err error) *MockCellMappingInterface_GetInternalCellUUID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockCellMappingInterface_GetInternalCellUUID_Call) RunAndReturn(run func(doorNumber int) (uuid.UUID, error)) *MockCellMappingInterface_GetInternalCellUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMapping provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) GetMapping() *entity.CellMapping {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMapping")
	}

	var r0 *entity.CellMapping
	if returnFunc, ok := ret.Get(0).(func() *entity.CellMapping); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CellMapping)
		}
	}
	return r0
}

// MockCellMappingInterface_GetMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMapping'
type MockCellMappingInterface_GetMapping_Call struct {
	*mock.Call
}

// GetMapping is a helper method to define mock.On call
func (_e *MockCellMappingInterface_Expecter) GetMapping() *MockCellMappingInterface_GetMapping_Call {
	return &MockCellMappingInterface_GetMapping_Call{Call: _e.mock.On("GetMapping")}
}

func (_c *MockCellMappingInterface_GetMapping_Call) Run(run func()) *MockCellMappingInterface_GetMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCellMappingInterface_GetMapping_Call) Return(cellMapping *entity.CellMapping) *MockCellMappingInterface_GetMapping_Call {
	_c.Call.Return(cellMapping)
	return _c
}

func (_c *MockCellMappingInterface_GetMapping_Call) RunAndReturn(run func() *entity.CellMapping) *MockCellMappingInterface_GetMapping_Call {
	_c.Call.Return(run)
	return _c
}

// IsInitialized provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) IsInitialized() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCellMappingInterface_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type MockCellMappingInterface_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *MockCellMappingInterface_Expecter) IsInitialized() *MockCellMappingInterface_IsInitialized_Call {
	return &MockCellMappingInterface_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *MockCellMappingInterface_IsInitialized_Call) Run(run func()) *MockCellMappingInterface_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCellMappingInterface_IsInitialized_Call) Return(b bool) *MockCellMappingInterface_IsInitialized_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCellMappingInterface_IsInitialized_Call) RunAndReturn(run func() bool) *MockCellMappingInterface_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockCellMappingInterface
func (_mock *MockCellMappingInterface) Sync(automatID uuid.UUID, external []uuid.UUID, internal []uuid.UUID) error {
	ret := _mock.Called(automatID, external, internal)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, []uuid.UUID, []uuid.UUID) error); ok {
		r0 = returnFunc(automatID, external, internal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCellMappingInterface_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockCellMappingInterface_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - automatID uuid.UUID
//   - external []uuid.UUID
//   - internal []uuid.UUID
func (_e *MockCellMappingInterface_Expecter) Sync(automatID interface{}, external interface{}, internal interface{}) *MockCellMappingInterface_Sync_Call {
	return &MockCellMappingInterface_Sync_Call{Call: _e.mock.On("Sync", automatID, external, internal)}
}

func (_c *MockCellMappingInterface_Sync_Call) Run(run func(automatID uuid.UUID, external []uuid.UUID, internal []uuid.UUID)) *MockCellMappingInterface_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCellMappingInterface_Sync_Call) Return(err error) *MockCellMappingInterface_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCellMappingInterface_Sync_Call) RunAndReturn(run func(automatID uuid.UUID, external []uuid.UUID, internal []uuid.UUID) error) *MockCellMappingInterface_Sync_Call {
	_c.Call.Return(run)
	return _c
}
