// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/locker-agent/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientInterface creates a new instance of MockClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientInterface {
	mock := &MockClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientInterface is an autogenerated mock type for the ClientInterface type
type MockClientInterface struct {
	mock.Mock
}

type MockClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientInterface) EXPECT() *MockClientInterface_Expecter {
	return &MockClientInterface_Expecter{mock: &_m.Mock}
}

// ConfirmLoaded provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) ConfirmLoaded(ctx context.Context, orderID uuid.UUID, lockerCellID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID, lockerCellID)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmLoaded")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID, lockerCellID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientInterface_ConfirmLoaded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmLoaded'
type MockClientInterface_ConfirmLoaded_Call struct {
	*mock.Call
}

// ConfirmLoaded is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - lockerCellID uuid.UUID
func (_e *MockClientInterface_Expecter) ConfirmLoaded(ctx interface{}, orderID interface{}, lockerCellID interface{}) *MockClientInterface_ConfirmLoaded_Call {
	return &MockClientInterface_ConfirmLoaded_Call{Call: _e.mock.On("ConfirmLoaded", ctx, orderID, lockerCellID)}
}

func (_c *MockClientInterface_ConfirmLoaded_Call) Run(run func(ctx context.Context, orderID uuid.UUID, lockerCellID uuid.UUID)) *MockClientInterface_ConfirmLoaded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientInterface_ConfirmLoaded_Call) Return(err error) *MockClientInterface_ConfirmLoaded_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientInterface_ConfirmLoaded_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, lockerCellID uuid.UUID) error) *MockClientInterface_ConfirmLoaded_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmPickup provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) ConfirmPickup(ctx context.Context, cellIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, cellIDs)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPickup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, cellIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClientInterface_ConfirmPickup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPickup'
type MockClientInterface_ConfirmPickup_Call struct {
	*mock.Call
}

// ConfirmPickup is a helper method to define mock.On call
//   - ctx context.Context
//   - cellIDs []uuid.UUID
func (_e *MockClientInterface_Expecter) ConfirmPickup(ctx interface{}, cellIDs interface{}) *MockClientInterface_ConfirmPickup_Call {
	return &MockClientInterface_ConfirmPickup_Call{Call: _e.mock.On("ConfirmPickup", ctx, cellIDs)}
}

func (_c *MockClientInterface_ConfirmPickup_Call) Run(run func(ctx context.Context, cellIDs []uuid.UUID)) *MockClientInterface_ConfirmPickup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClientInterface_ConfirmPickup_Call) Return(err error) *MockClientInterface_ConfirmPickup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClientInterface_ConfirmPickup_Call) RunAndReturn(run func(ctx context.Context, cellIDs []uuid.UUID) error) *MockClientInterface_ConfirmPickup_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQR provides a mock function for the type MockClientInterface
func (_mock *MockClientInterface) ValidateQR(ctx context.Context, qrData string, parcelAutomatID string) (*entity.QRValidationResponse, error) {
	ret := _mock.Called(ctx, qrData, parcelAutomatID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQR")
	}

	var r0 *entity.QRValidationResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*entity.QRValidationResponse, error)); ok {
		return returnFunc(ctx, qrData, parcelAutomatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *entity.QRValidationResponse); ok {
		r0 = returnFunc(ctx, qrData, parcelAutomatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.QRValidationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, qrData, parcelAutomatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClientInterface_ValidateQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQR'
type MockClientInterface_ValidateQR_Call struct {
	*mock.Call
}

// ValidateQR is a helper method to define mock.On call
//   - ctx context.Context
//   - qrData string
//   - parcelAutomatID string
func (_e *MockClientInterface_Expecter) ValidateQR(ctx interface{}, qrData interface{}, parcelAutomatID interface{}) *MockClientInterface_ValidateQR_Call {
	return &MockClientInterface_ValidateQR_Call{Call: _e.mock.On("ValidateQR", ctx, qrData, parcelAutomatID)}
}

func (_c *MockClientInterface_ValidateQR_Call) Run(run func(ctx context.Context, qrData string, parcelAutomatID string)) *MockClientInterface_ValidateQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClientInterface_ValidateQR_Call) Return(qRValidationResponse *entity.QRValidationResponse, err error) *MockClientInterface_ValidateQR_Call {
	_c.Call.Return(qRValidationResponse, err)
	return _c
}

func (_c *MockClientInterface_ValidateQR_Call) RunAndReturn(run func(ctx context.Context, qrData string, parcelAutomatID string) (*entity.QRValidationResponse, error)) *MockClientInterface_ValidateQR_Call {
	_c.Call.Return(run)
	return _c
}
