// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockDisplayInterface creates a new instance of MockDisplayInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDisplayInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDisplayInterface {
	mock := &MockDisplayInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDisplayInterface is an autogenerated mock type for the DisplayInterface type
type MockDisplayInterface struct {
	mock.Mock
}

type MockDisplayInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDisplayInterface) EXPECT() *MockDisplayInterface_Expecter {
	return &MockDisplayInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDisplayInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) Close() *MockDisplayInterface_Close_Call {
	return &MockDisplayInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDisplayInterface_Close_Call) Run(run func()) *MockDisplayInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_Close_Call) Return(err error) *MockDisplayInterface_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_Close_Call) RunAndReturn(run func() error) *MockDisplayInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// IsMockMode provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) IsMockMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsMockMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDisplayInterface_IsMockMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMockMode'
type MockDisplayInterface_IsMockMode_Call struct {
	*mock.Call
}

// IsMockMode is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) IsMockMode() *MockDisplayInterface_IsMockMode_Call {
	return &MockDisplayInterface_IsMockMode_Call{Call: _e.mock.On("IsMockMode")}
}

func (_c *MockDisplayInterface_IsMockMode_Call) Run(run func()) *MockDisplayInterface_IsMockMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_IsMockMode_Call) Return(b bool) *MockDisplayInterface_IsMockMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDisplayInterface_IsMockMode_Call) RunAndReturn(run func() bool) *MockDisplayInterface_IsMockMode_Call {
	_c.Call.Return(run)
	return _c
}

// ShowCellOpened provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowCellOpened(cellNumber int) error {
	ret := _mock.Called(cellNumber)

	if len(ret) == 0 {
		panic("no return value specified for ShowCellOpened")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(cellNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowCellOpened_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowCellOpened'
type MockDisplayInterface_ShowCellOpened_Call struct {
	*mock.Call
}

// ShowCellOpened is a helper method to define mock.On call
//   - cellNumber int
func (_e *MockDisplayInterface_Expecter) ShowCellOpened(cellNumber interface{}) *MockDisplayInterface_ShowCellOpened_Call {
	return &MockDisplayInterface_ShowCellOpened_Call{Call: _e.mock.On("ShowCellOpened", cellNumber)}
}

func (_c *MockDisplayInterface_ShowCellOpened_Call) Run(run func(cellNumber int)) *MockDisplayInterface_ShowCellOpened_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplayInterface_ShowCellOpened_Call) Return(err error) *MockDisplayInterface_ShowCellOpened_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowCellOpened_Call) RunAndReturn(run func(cellNumber int) error) *MockDisplayInterface_ShowCellOpened_Call {
	_c.Call.Return(run)
	return _c
}

// ShowCellOpening provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowCellOpening(cellNumber int, orderNumber string) error {
	ret := _mock.Called(cellNumber, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for ShowCellOpening")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(cellNumber, orderNumber)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowCellOpening_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowCellOpening'
type MockDisplayInterface_ShowCellOpening_Call struct {
	*mock.Call
}

// ShowCellOpening is a helper method to define mock.On call
//   - cellNumber int
//   - orderNumber string
func (_e *MockDisplayInterface_Expecter) ShowCellOpening(cellNumber interface{}, orderNumber interface{}) *MockDisplayInterface_ShowCellOpening_Call {
	return &MockDisplayInterface_ShowCellOpening_Call{Call: _e.mock.On("ShowCellOpening", cellNumber, orderNumber)}
}

func (_c *MockDisplayInterface_ShowCellOpening_Call) Run(run func(cellNumber int, orderNumber string)) *MockDisplayInterface_ShowCellOpening_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDisplayInterface_ShowCellOpening_Call) Return(err error) *MockDisplayInterface_ShowCellOpening_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowCellOpening_Call) RunAndReturn(run func(cellNumber int, orderNumber string) error) *MockDisplayInterface_ShowCellOpening_Call {
	_c.Call.Return(run)
	return _c
}

// ShowError provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowError(message string) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ShowError")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowError'
type MockDisplayInterface_ShowError_Call struct {
	*mock.Call
}

// ShowError is a helper method to define mock.On call
//   - message string
func (_e *MockDisplayInterface_Expecter) ShowError(message interface{}) *MockDisplayInterface_ShowError_Call {
	return &MockDisplayInterface_ShowError_Call{Call: _e.mock.On("ShowError", message)}
}

func (_c *MockDisplayInterface_ShowError_Call) Run(run func(message string)) *MockDisplayInterface_ShowError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplayInterface_ShowError_Call) Return(err error) *MockDisplayInterface_ShowError_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowError_Call) RunAndReturn(run func(message string) error) *MockDisplayInterface_ShowError_Call {
	_c.Call.Return(run)
	return _c
}

// ShowInvalid provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowInvalid() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowInvalid")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowInvalid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowInvalid'
type MockDisplayInterface_ShowInvalid_Call struct {
	*mock.Call
}

// ShowInvalid is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) ShowInvalid() *MockDisplayInterface_ShowInvalid_Call {
	return &MockDisplayInterface_ShowInvalid_Call{Call: _e.mock.On("ShowInvalid")}
}

func (_c *MockDisplayInterface_ShowInvalid_Call) Run(run func()) *MockDisplayInterface_ShowInvalid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_ShowInvalid_Call) Return(err error) *MockDisplayInterface_ShowInvalid_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowInvalid_Call) RunAndReturn(run func() error) *MockDisplayInterface_ShowInvalid_Call {
	_c.Call.Return(run)
	return _c
}

// ShowPleaseClose provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowPleaseClose() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowPleaseClose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowPleaseClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowPleaseClose'
type MockDisplayInterface_ShowPleaseClose_Call struct {
	*mock.Call
}

// ShowPleaseClose is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) ShowPleaseClose() *MockDisplayInterface_ShowPleaseClose_Call {
	return &MockDisplayInterface_ShowPleaseClose_Call{Call: _e.mock.On("ShowPleaseClose")}
}

func (_c *MockDisplayInterface_ShowPleaseClose_Call) Run(run func()) *MockDisplayInterface_ShowPleaseClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_ShowPleaseClose_Call) Return(err error) *MockDisplayInterface_ShowPleaseClose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowPleaseClose_Call) RunAndReturn(run func() error) *MockDisplayInterface_ShowPleaseClose_Call {
	_c.Call.Return(run)
	return _c
}

// ShowScanning provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowScanning() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowScanning")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowScanning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowScanning'
type MockDisplayInterface_ShowScanning_Call struct {
	*mock.Call
}

// ShowScanning is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) ShowScanning() *MockDisplayInterface_ShowScanning_Call {
	return &MockDisplayInterface_ShowScanning_Call{Call: _e.mock.On("ShowScanning")}
}

func (_c *MockDisplayInterface_ShowScanning_Call) Run(run func()) *MockDisplayInterface_ShowScanning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_ShowScanning_Call) Return(err error) *MockDisplayInterface_ShowScanning_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowScanning_Call) RunAndReturn(run func() error) *MockDisplayInterface_ShowScanning_Call {
	_c.Call.Return(run)
	return _c
}

// ShowSuccess provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowSuccess(message string) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for ShowSuccess")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowSuccess'
type MockDisplayInterface_ShowSuccess_Call struct {
	*mock.Call
}

// ShowSuccess is a helper method to define mock.On call
//   - message string
func (_e *MockDisplayInterface_Expecter) ShowSuccess(message interface{}) *MockDisplayInterface_ShowSuccess_Call {
	return &MockDisplayInterface_ShowSuccess_Call{Call: _e.mock.On("ShowSuccess", message)}
}

func (_c *MockDisplayInterface_ShowSuccess_Call) Run(run func(message string)) *MockDisplayInterface_ShowSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDisplayInterface_ShowSuccess_Call) Return(err error) *MockDisplayInterface_ShowSuccess_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowSuccess_Call) RunAndReturn(run func(message string) error) *MockDisplayInterface_ShowSuccess_Call {
	_c.Call.Return(run)
	return _c
}

// ShowThankYou provides a mock function for the type MockDisplayInterface
func (_mock *MockDisplayInterface) ShowThankYou() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowThankYou")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDisplayInterface_ShowThankYou_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowThankYou'
type MockDisplayInterface_ShowThankYou_Call struct {
	*mock.Call
}

// ShowThankYou is a helper method to define mock.On call
func (_e *MockDisplayInterface_Expecter) ShowThankYou() *MockDisplayInterface_ShowThankYou_Call {
	return &MockDisplayInterface_ShowThankYou_Call{Call: _e.mock.On("ShowThankYou")}
}

func (_c *MockDisplayInterface_ShowThankYou_Call) Run(run func()) *MockDisplayInterface_ShowThankYou_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDisplayInterface_ShowThankYou_Call) Return(err error) *MockDisplayInterface_ShowThankYou_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDisplayInterface_ShowThankYou_Call) RunAndReturn(run func() error) *MockDisplayInterface_ShowThankYou_Call {
	_c.Call.Return(run)
	return _c
}
