// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQRCameraInterface creates a new instance of MockQRCameraInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRCameraInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRCameraInterface {
	mock := &MockQRCameraInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQRCameraInterface is an autogenerated mock type for the QRCameraInterface type
type MockQRCameraInterface struct {
	mock.Mock
}

type MockQRCameraInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRCameraInterface) EXPECT() *MockQRCameraInterface_Expecter {
	return &MockQRCameraInterface_Expecter{mock: &_m.Mock}
}

// GetResultChannel provides a mock function for the type MockQRCameraInterface
func (_mock *MockQRCameraInterface) GetResultChannel() <-chan string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetResultChannel")
	}

	var r0 <-chan string
	if returnFunc, ok := ret.Get(0).(func() <-chan string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}
	return r0
}

// MockQRCameraInterface_GetResultChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResultChannel'
type MockQRCameraInterface_GetResultChannel_Call struct {
	*mock.Call
}

// GetResultChannel is a helper method to define mock.On call
func (_e *MockQRCameraInterface_Expecter) GetResultChannel() *MockQRCameraInterface_GetResultChannel_Call {
	return &MockQRCameraInterface_GetResultChannel_Call{Call: _e.mock.On("GetResultChannel")}
}

func (_c *MockQRCameraInterface_GetResultChannel_Call) Run(run func()) *MockQRCameraInterface_GetResultChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQRCameraInterface_GetResultChannel_Call) Return(stringCh <-chan string) *MockQRCameraInterface_GetResultChannel_Call {
	_c.Call.Return(stringCh)
	return _c
}

func (_c *MockQRCameraInterface_GetResultChannel_Call) RunAndReturn(run func() <-chan string) *MockQRCameraInterface_GetResultChannel_Call {
	_c.Call.Return(run)
	return _c
}

// IsMockMode provides a mock function for the type MockQRCameraInterface
func (_mock *MockQRCameraInterface) IsMockMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsMockMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQRCameraInterface_IsMockMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMockMode'
type MockQRCameraInterface_IsMockMode_Call struct {
	*mock.Call
}

// IsMockMode is a helper method to define mock.On call
func (_e *MockQRCameraInterface_Expecter) IsMockMode() *MockQRCameraInterface_IsMockMode_Call {
	return &MockQRCameraInterface_IsMockMode_Call{Call: _e.mock.On("IsMockMode")}
}

func (_c *MockQRCameraInterface_IsMockMode_Call) Run(run func()) *MockQRCameraInterface_IsMockMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQRCameraInterface_IsMockMode_Call) Return(b bool) *MockQRCameraInterface_IsMockMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQRCameraInterface_IsMockMode_Call) RunAndReturn(run func() bool) *MockQRCameraInterface_IsMockMode_Call {
	_c.Call.Return(run)
	return _c
}

// ScanOnce provides a mock function for the type MockQRCameraInterface
func (_mock *MockQRCameraInterface) ScanOnce() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ScanOnce")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRCameraInterface_ScanOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScanOnce'
type MockQRCameraInterface_ScanOnce_Call struct {
	*mock.Call
}

// ScanOnce is a helper method to define mock.On call
func (_e *MockQRCameraInterface_Expecter) ScanOnce() *MockQRCameraInterface_ScanOnce_Call {
	return &MockQRCameraInterface_ScanOnce_Call{Call: _e.mock.On("ScanOnce")}
}

func (_c *MockQRCameraInterface_ScanOnce_Call) Run(run func()) *MockQRCameraInterface_ScanOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQRCameraInterface_ScanOnce_Call) Return(s string, err error) *MockQRCameraInterface_ScanOnce_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQRCameraInterface_ScanOnce_Call) RunAndReturn(run func() (string, error)) *MockQRCameraInterface_ScanOnce_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockQRCameraInterface
func (_mock *MockQRCameraInterface) Start(ctx context.Context) {
	_mock.Called(ctx)
	return
}

// MockQRCameraInterface_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockQRCameraInterface_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQRCameraInterface_Expecter) Start(ctx interface{}) *MockQRCameraInterface_Start_Call {
	return &MockQRCameraInterface_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockQRCameraInterface_Start_Call) Run(run func(ctx context.Context)) *MockQRCameraInterface_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQRCameraInterface_Start_Call) Return() *MockQRCameraInterface_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQRCameraInterface_Start_Call) RunAndReturn(run func(ctx context.Context)) *MockQRCameraInterface_Start_Call {
	_c.Run(run)
	return _c
}

// Stop provides a mock function for the type MockQRCameraInterface
func (_mock *MockQRCameraInterface) Stop() {
	_mock.Called()
	return
}

// MockQRCameraInterface_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockQRCameraInterface_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockQRCameraInterface_Expecter) Stop() *MockQRCameraInterface_Stop_Call {
	return &MockQRCameraInterface_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockQRCameraInterface_Stop_Call) Run(run func()) *MockQRCameraInterface_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQRCameraInterface_Stop_Call) Return() *MockQRCameraInterface_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQRCameraInterface_Stop_Call) RunAndReturn(run func()) *MockQRCameraInterface_Stop_Call {
	_c.Run(run)
	return _c
}
