// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at
`

type CreateDeliveryParams struct {
	OrderID              uuid.UUID   `json:"order_id"`
	DroneID              pgtype.UUID `json:"drone_id"`
	ParcelAutomatID      uuid.UUID   `json:"parcel_automat_id"`
	InternalLockerCellID pgtype.UUID `json:"internal_locker_cell_id"`
	Status               string      `json:"status"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery,
		arg.OrderID,
		arg.DroneID,
		arg.ParcelAutomatID,
		arg.InternalLockerCellID,
		arg.Status,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DroneID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteDelivery = `-- name: DeleteDelivery :exec
DELETE FROM deliveries
WHERE id = $1
`

func (q *Queries) DeleteDelivery(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDelivery, id)
	return err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at FROM deliveries
WHERE id = $1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DroneID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeliveryByOrderID = `-- name: GetDeliveryByOrderID :one
SELECT id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at FROM deliveries
WHERE order_id = $1
`

func (q *Queries) GetDeliveryByOrderID(ctx context.Context, orderID uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByOrderID, orderID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DroneID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listDeliveries = `-- name: ListDeliveries :many
SELECT id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at FROM deliveries
ORDER BY id DESC
`

func (q *Queries) ListDeliveries(ctx context.Context) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DroneID,
			&i.ParcelAutomatID,
			&i.InternalLockerCellID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveriesByStatus = `-- name: ListDeliveriesByStatus :many
SELECT id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at FROM deliveries
WHERE status = $1
ORDER BY id DESC
`

func (q *Queries) ListDeliveriesByStatus(ctx context.Context, status string) ([]Delivery, error) {
	rows, err := q.db.Query(ctx, listDeliveriesByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Delivery
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DroneID,
			&i.ParcelAutomatID,
			&i.InternalLockerCellID,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeliveryDrone = `-- name: UpdateDeliveryDrone :one
UPDATE deliveries
SET drone_id = $2
WHERE id = $1
RETURNING id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at
`

type UpdateDeliveryDroneParams struct {
	ID      uuid.UUID   `json:"id"`
	DroneID pgtype.UUID `json:"drone_id"`
}

func (q *Queries) UpdateDeliveryDrone(ctx context.Context, arg UpdateDeliveryDroneParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryDrone, arg.ID, arg.DroneID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DroneID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :one
UPDATE deliveries
SET status = $2
WHERE id = $1
RETURNING id, order_id, drone_id, parcel_automat_id, internal_locker_cell_id, status, started_at, completed_at
`

type UpdateDeliveryStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DroneID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
