// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE FROM user_devices
WHERE token = $1
`

func (q *Queries) DeleteDeviceByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, token)
	return err
}

const listDevicesByUserID = `-- name: ListDevicesByUserID :many
SELECT id, user_id, token, platform, created_at, updated_at FROM user_devices
WHERE user_id = $1
`

func (q *Queries) ListDevicesByUserID(ctx context.Context, userID uuid.UUID) ([]UserDevice, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDevice
	for rows.Next() {
		var i UserDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO user_devices (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    updated_at = NOW()
RETURNING id, user_id, token, platform, created_at, updated_at
`

type UpsertDeviceParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Token    string    `json:"token"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (UserDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.Token, arg.Platform)
	var i UserDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
