// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drones.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDrone = `-- name: CreateDrone :one
INSERT INTO drones (model, status, ip_address)
VALUES ($1, $2, $3)
RETURNING id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at
`

type CreateDroneParams struct {
	Model     string `json:"model"`
	Status    string `json:"status"`
	IpAddress string `json:"ip_address"`
}

func (q *Queries) CreateDrone(ctx context.Context, arg CreateDroneParams) (Drone, error) {
	row := q.db.QueryRow(ctx, createDrone, arg.Model, arg.Status, arg.IpAddress)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.IpAddress,
		&i.Status,
		&i.BatteryLevel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.CurrentDeliveryID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDrone = `-- name: DeleteDrone :exec
DELETE FROM drones
WHERE id = $1
`

func (q *Queries) DeleteDrone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDrone, id)
	return err
}

const getAvailableDrone = `-- name: GetAvailableDrone :one
SELECT id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at FROM drones
WHERE status = 'idle'
LIMIT 1
`

func (q *Queries) GetAvailableDrone(ctx context.Context) (Drone, error) {
	row := q.db.QueryRow(ctx, getAvailableDrone)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.IpAddress,
		&i.Status,
		&i.BatteryLevel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.CurrentDeliveryID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDroneByID = `-- name: GetDroneByID :one
SELECT id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at FROM drones
WHERE id = $1
`

func (q *Queries) GetDroneByID(ctx context.Context, id uuid.UUID) (Drone, error) {
	row := q.db.QueryRow(ctx, getDroneByID, id)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.IpAddress,
		&i.Status,
		&i.BatteryLevel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.CurrentDeliveryID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDrones = `-- name: ListDrones :many
SELECT id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at FROM drones
ORDER BY id
`

func (q *Queries) ListDrones(ctx context.Context) ([]Drone, error) {
	rows, err := q.db.Query(ctx, listDrones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Drone
	for rows.Next() {
		var i Drone
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.IpAddress,
			&i.Status,
			&i.BatteryLevel,
			&i.Latitude,
			&i.Longitude,
			&i.Altitude,
			&i.Speed,
			&i.CurrentDeliveryID,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDrone = `-- name: UpdateDrone :one
UPDATE drones
SET model = $2, ip_address = $3, status = $4
WHERE id = $1
RETURNING id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at
`

type UpdateDroneParams struct {
	ID        uuid.UUID `json:"id"`
	Model     string    `json:"model"`
	IpAddress string    `json:"ip_address"`
	Status    string    `json:"status"`
}

func (q *Queries) UpdateDrone(ctx context.Context, arg UpdateDroneParams) (Drone, error) {
	row := q.db.QueryRow(ctx, updateDrone,
		arg.ID,
		arg.Model,
		arg.IpAddress,
		arg.Status,
	)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.IpAddress,
		&i.Status,
		&i.BatteryLevel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.CurrentDeliveryID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDroneStatus = `-- name: UpdateDroneStatus :one
UPDATE drones
SET status = $2
WHERE id = $1
RETURNING id, model, ip_address, status, battery_level, latitude, longitude, altitude, speed, current_delivery_id, error_message, created_at, updated_at
`

type UpdateDroneStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDroneStatus(ctx context.Context, arg UpdateDroneStatusParams) (Drone, error) {
	row := q.db.QueryRow(ctx, updateDroneStatus, arg.ID, arg.Status)
	var i Drone
	err := row.Scan(
		&i.ID,
		&i.Model,
		&i.IpAddress,
		&i.Status,
		&i.BatteryLevel,
		&i.Latitude,
		&i.Longitude,
		&i.Altitude,
		&i.Speed,
		&i.CurrentDeliveryID,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
