// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Delivery struct {
	ID                   uuid.UUID        `json:"id"`
	OrderID              uuid.UUID        `json:"order_id"`
	DroneID              pgtype.UUID      `json:"drone_id"`
	ParcelAutomatID      uuid.UUID        `json:"parcel_automat_id"`
	InternalLockerCellID pgtype.UUID      `json:"internal_locker_cell_id"`
	Status               string           `json:"status"`
	StartedAt            pgtype.Timestamp `json:"started_at"`
	CompletedAt          pgtype.Timestamp `json:"completed_at"`
}

type Drone struct {
	ID                uuid.UUID        `json:"id"`
	Model             string           `json:"model"`
	IpAddress         string           `json:"ip_address"`
	Status            string           `json:"status"`
	BatteryLevel      pgtype.Numeric   `json:"battery_level"`
	Latitude          pgtype.Numeric   `json:"latitude"`
	Longitude         pgtype.Numeric   `json:"longitude"`
	Altitude          pgtype.Numeric   `json:"altitude"`
	Speed             pgtype.Numeric   `json:"speed"`
	CurrentDeliveryID pgtype.UUID      `json:"current_delivery_id"`
	ErrorMessage      *string          `json:"error_message"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type Good struct {
	ID                uuid.UUID `json:"id"`
	Name              string    `json:"name"`
	Weight            float64   `json:"weight"`
	Height            float64   `json:"height"`
	Length            float64   `json:"length"`
	Width             float64   `json:"width"`
	QuantityAvailable int32     `json:"quantity_available"`
}

type LockerCellsInternal struct {
	ID         uuid.UUID `json:"id"`
	PostID     uuid.UUID `json:"post_id"`
	Height     float64   `json:"height"`
	Length     float64   `json:"length"`
	Width      float64   `json:"width"`
	Status     string    `json:"status"`
	CellNumber *int32    `json:"cell_number"`
}

type LockerCellsOut struct {
	ID         uuid.UUID `json:"id"`
	PostID     uuid.UUID `json:"post_id"`
	Height     float64   `json:"height"`
	Length     float64   `json:"length"`
	Width      float64   `json:"width"`
	Status     string    `json:"status"`
	CellNumber *int32    `json:"cell_number"`
}

type Order struct {
	ID              uuid.UUID        `json:"id"`
	UserID          uuid.UUID        `json:"user_id"`
	GoodID          uuid.UUID        `json:"good_id"`
	ParcelAutomatID uuid.UUID        `json:"parcel_automat_id"`
	LockerCellID    pgtype.UUID      `json:"locker_cell_id"`
	Status          string           `json:"status"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type ParcelAutomat struct {
	ID            uuid.UUID `json:"id"`
	City          string    `json:"city"`
	Address       string    `json:"address"`
	NumberOfCells int32     `json:"number_of_cells"`
	IpAddress     string    `json:"ip_address"`
	Coordinates   string    `json:"coordinates"`
	ArucoID       int32     `json:"aruco_id"`
	IsWorking     bool      `json:"is_working"`
}

type User struct {
	ID               uuid.UUID        `json:"id"`
	FullName         string           `json:"full_name"`
	Email            *string          `json:"email"`
	PhoneNumber      *string          `json:"phone_number"`
	PassHash         *string          `json:"pass_hash"`
	PhoneVerified    bool             `json:"phone_verified"`
	VerificationCode *string          `json:"verification_code"`
	CodeExpiresAt    pgtype.Timestamp `json:"code_expires_at"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	Role             string           `json:"role"`
	QrIssuedAt       pgtype.Timestamp `json:"qr_issued_at"`
	QrExpiresAt      pgtype.Timestamp `json:"qr_expires_at"`
}

type UserDevice struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	Platform  string           `json:"platform"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
