// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, good_id, parcel_automat_id, locker_cell_id, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, good_id, parcel_automat_id, locker_cell_id, status, created_at
`

type CreateOrderParams struct {
	UserID          uuid.UUID   `json:"user_id"`
	GoodID          uuid.UUID   `json:"good_id"`
	ParcelAutomatID uuid.UUID   `json:"parcel_automat_id"`
	LockerCellID    pgtype.UUID `json:"locker_cell_id"`
	Status          string      `json:"status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.GoodID,
		arg.ParcelAutomatID,
		arg.LockerCellID,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoodID,
		&i.ParcelAutomatID,
		&i.LockerCellID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, good_id, parcel_automat_id, locker_cell_id, status, created_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoodID,
		&i.ParcelAutomatID,
		&i.LockerCellID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByLockerCellID = `-- name: GetOrderByLockerCellID :one
SELECT id, user_id, good_id, parcel_automat_id, locker_cell_id, status, created_at FROM orders
WHERE locker_cell_id = $1
`

func (q *Queries) GetOrderByLockerCellID(ctx context.Context, lockerCellID pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByLockerCellID, lockerCellID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoodID,
		&i.ParcelAutomatID,
		&i.LockerCellID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, good_id, parcel_automat_id, locker_cell_id, status, created_at FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoodID,
			&i.ParcelAutomatID,
			&i.LockerCellID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT 
    o.id,
    o.user_id,
    o.good_id,
    o.parcel_automat_id,
    o.locker_cell_id,
    o.status,
    o.created_at,
    g.id as "good.id",
    g.name as "good.name",
    g.weight as "good.weight",
    g.height as "good.height",
    g.length as "good.length",
    g.width as "good.width",
    g.quantity_available as "good.quantity_available"
FROM orders o
LEFT JOIN goods g ON o.good_id = g.id
WHERE o.user_id = $1
ORDER BY o.created_at DESC
`

type ListOrdersByUserIDRow struct {
	ID                    uuid.UUID        `json:"id"`
	UserID                uuid.UUID        `json:"user_id"`
	GoodID                uuid.UUID        `json:"good_id"`
	ParcelAutomatID       uuid.UUID        `json:"parcel_automat_id"`
	LockerCellID          pgtype.UUID      `json:"locker_cell_id"`
	Status                string           `json:"status"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	GoodID_2              pgtype.UUID      `json:"good.id_2"`
	GoodName              *string          `json:"good.name"`
	GoodWeight            pgtype.Numeric   `json:"good.weight"`
	GoodHeight            pgtype.Numeric   `json:"good.height"`
	GoodLength            pgtype.Numeric   `json:"good.length"`
	GoodWidth             pgtype.Numeric   `json:"good.width"`
	GoodQuantityAvailable *int32           `json:"good.quantity_available"`
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]ListOrdersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersByUserIDRow
	for rows.Next() {
		var i ListOrdersByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GoodID,
			&i.ParcelAutomatID,
			&i.LockerCellID,
			&i.Status,
			&i.CreatedAt,
			&i.GoodID_2,
			&i.GoodName,
			&i.GoodWeight,
			&i.GoodHeight,
			&i.GoodLength,
			&i.GoodWidth,
			&i.GoodQuantityAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2
WHERE id = $1
RETURNING id, user_id, good_id, parcel_automat_id, locker_cell_id, status, created_at
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GoodID,
		&i.ParcelAutomatID,
		&i.LockerCellID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
