// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parcel_automats.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createParcelAutomat = `-- name: CreateParcelAutomat :one
INSERT INTO parcel_automats (city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working
`

type CreateParcelAutomatParams struct {
	City          string `json:"city"`
	Address       string `json:"address"`
	NumberOfCells int32  `json:"number_of_cells"`
	IpAddress     string `json:"ip_address"`
	Coordinates   string `json:"coordinates"`
	ArucoID       int32  `json:"aruco_id"`
	IsWorking     bool   `json:"is_working"`
}

func (q *Queries) CreateParcelAutomat(ctx context.Context, arg CreateParcelAutomatParams) (ParcelAutomat, error) {
	row := q.db.QueryRow(ctx, createParcelAutomat,
		arg.City,
		arg.Address,
		arg.NumberOfCells,
		arg.IpAddress,
		arg.Coordinates,
		arg.ArucoID,
		arg.IsWorking,
	)
	var i ParcelAutomat
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Address,
		&i.NumberOfCells,
		&i.IpAddress,
		&i.Coordinates,
		&i.ArucoID,
		&i.IsWorking,
	)
	return i, err
}

const deleteParcelAutomat = `-- name: DeleteParcelAutomat :exec
DELETE FROM parcel_automats
WHERE id = $1
`

func (q *Queries) DeleteParcelAutomat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteParcelAutomat, id)
	return err
}

const getParcelAutomatByID = `-- name: GetParcelAutomatByID :one
SELECT id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working FROM parcel_automats
WHERE id = $1
`

func (q *Queries) GetParcelAutomatByID(ctx context.Context, id uuid.UUID) (ParcelAutomat, error) {
	row := q.db.QueryRow(ctx, getParcelAutomatByID, id)
	var i ParcelAutomat
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Address,
		&i.NumberOfCells,
		&i.IpAddress,
		&i.Coordinates,
		&i.ArucoID,
		&i.IsWorking,
	)
	return i, err
}

const listParcelAutomats = `-- name: ListParcelAutomats :many
SELECT id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working FROM parcel_automats
ORDER BY id
`

func (q *Queries) ListParcelAutomats(ctx context.Context) ([]ParcelAutomat, error) {
	rows, err := q.db.Query(ctx, listParcelAutomats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParcelAutomat
	for rows.Next() {
		var i ParcelAutomat
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.Address,
			&i.NumberOfCells,
			&i.IpAddress,
			&i.Coordinates,
			&i.ArucoID,
			&i.IsWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkingParcelAutomats = `-- name: ListWorkingParcelAutomats :many
SELECT id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working FROM parcel_automats
WHERE is_working = true
ORDER BY city, address
`

func (q *Queries) ListWorkingParcelAutomats(ctx context.Context) ([]ParcelAutomat, error) {
	rows, err := q.db.Query(ctx, listWorkingParcelAutomats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParcelAutomat
	for rows.Next() {
		var i ParcelAutomat
		if err := rows.Scan(
			&i.ID,
			&i.City,
			&i.Address,
			&i.NumberOfCells,
			&i.IpAddress,
			&i.Coordinates,
			&i.ArucoID,
			&i.IsWorking,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParcelAutomat = `-- name: UpdateParcelAutomat :one
UPDATE parcel_automats
SET city = $2, address = $3, ip_address = $4, coordinates = $5
WHERE id = $1
RETURNING id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working
`

type UpdateParcelAutomatParams struct {
	ID          uuid.UUID `json:"id"`
	City        string    `json:"city"`
	Address     string    `json:"address"`
	IpAddress   string    `json:"ip_address"`
	Coordinates string    `json:"coordinates"`
}

func (q *Queries) UpdateParcelAutomat(ctx context.Context, arg UpdateParcelAutomatParams) (ParcelAutomat, error) {
	row := q.db.QueryRow(ctx, updateParcelAutomat,
		arg.ID,
		arg.City,
		arg.Address,
		arg.IpAddress,
		arg.Coordinates,
	)
	var i ParcelAutomat
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Address,
		&i.NumberOfCells,
		&i.IpAddress,
		&i.Coordinates,
		&i.ArucoID,
		&i.IsWorking,
	)
	return i, err
}

const updateParcelAutomatStatus = `-- name: UpdateParcelAutomatStatus :one
UPDATE parcel_automats
SET is_working = $2
WHERE id = $1
RETURNING id, city, address, number_of_cells, ip_address, coordinates, aruco_id, is_working
`

type UpdateParcelAutomatStatusParams struct {
	ID        uuid.UUID `json:"id"`
	IsWorking bool      `json:"is_working"`
}

func (q *Queries) UpdateParcelAutomatStatus(ctx context.Context, arg UpdateParcelAutomatStatusParams) (ParcelAutomat, error) {
	row := q.db.QueryRow(ctx, updateParcelAutomatStatus, arg.ID, arg.IsWorking)
	var i ParcelAutomat
	err := row.Scan(
		&i.ID,
		&i.City,
		&i.Address,
		&i.NumberOfCells,
		&i.IpAddress,
		&i.Coordinates,
		&i.ArucoID,
		&i.IsWorking,
	)
	return i, err
}
