// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, phone_number, pass_hash, role)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type CreateUserParams struct {
	FullName    string  `json:"full_name"`
	Email       *string `json:"email"`
	PhoneNumber *string `json:"phone_number"`
	PassHash    *string `json:"pass_hash"`
	Role        string  `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.PassHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const createUserWithCustomDate = `-- name: CreateUserWithCustomDate :one
INSERT INTO users (full_name, email, phone_number, pass_hash, role, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type CreateUserWithCustomDateParams struct {
	FullName    string           `json:"full_name"`
	Email       *string          `json:"email"`
	PhoneNumber *string          `json:"phone_number"`
	PassHash    *string          `json:"pass_hash"`
	Role        string           `json:"role"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUserWithCustomDate(ctx context.Context, arg CreateUserWithCustomDateParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithCustomDate,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
		arg.PassHash,
		arg.Role,
		arg.CreatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at FROM users
WHERE phone_number = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneNumber *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.PhoneNumber,
			&i.PassHash,
			&i.PhoneVerified,
			&i.VerificationCode,
			&i.CodeExpiresAt,
			&i.CreatedAt,
			&i.Role,
			&i.QrIssuedAt,
			&i.QrExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET full_name = $2, email = $3, phone_number = $4
WHERE id = $1
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type UpdateUserParams struct {
	ID          uuid.UUID `json:"id"`
	FullName    string    `json:"full_name"`
	Email       *string   `json:"email"`
	PhoneNumber *string   `json:"phone_number"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET pass_hash = $2
WHERE id = $1
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type UpdateUserPasswordParams struct {
	ID       uuid.UUID `json:"id"`
	PassHash *string   `json:"pass_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.PassHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const updateUserQR = `-- name: UpdateUserQR :one
UPDATE users
SET qr_issued_at = $2, qr_expires_at = $3
WHERE id = $1
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type UpdateUserQRParams struct {
	ID          uuid.UUID        `json:"id"`
	QrIssuedAt  pgtype.Timestamp `json:"qr_issued_at"`
	QrExpiresAt pgtype.Timestamp `json:"qr_expires_at"`
}

func (q *Queries) UpdateUserQR(ctx context.Context, arg UpdateUserQRParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserQR, arg.ID, arg.QrIssuedAt, arg.QrExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const updateUserVerificationCode = `-- name: UpdateUserVerificationCode :one
UPDATE users
SET verification_code = $2, code_expires_at = $3
WHERE id = $1
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

type UpdateUserVerificationCodeParams struct {
	ID               uuid.UUID        `json:"id"`
	VerificationCode *string          `json:"verification_code"`
	CodeExpiresAt    pgtype.Timestamp `json:"code_expires_at"`
}

func (q *Queries) UpdateUserVerificationCode(ctx context.Context, arg UpdateUserVerificationCodeParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserVerificationCode, arg.ID, arg.VerificationCode, arg.CodeExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}

const verifyUserPhone = `-- name: VerifyUserPhone :one
UPDATE users
SET phone_verified = true, verification_code = NULL, code_expires_at = NULL
WHERE id = $1
RETURNING id, full_name, email, phone_number, pass_hash, phone_verified, verification_code, code_expires_at, created_at, role, qr_issued_at, qr_expires_at
`

func (q *Queries) VerifyUserPhone(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyUserPhone, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.PhoneNumber,
		&i.PassHash,
		&i.PhoneVerified,
		&i.VerificationCode,
		&i.CodeExpiresAt,
		&i.CreatedAt,
		&i.Role,
		&i.QrIssuedAt,
		&i.QrExpiresAt,
	)
	return i, err
}
