// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeliveryTask = `-- name: GetDeliveryTask :one
SELECT 
    d.id,
    d.order_id,
    o.good_id,
    o.locker_cell_id,
    d.parcel_automat_id,
    d.internal_locker_cell_id,
    d.status,
    d.started_at,
    d.completed_at,
    d.drone_id
FROM deliveries d
JOIN orders o ON d.order_id = o.id
WHERE d.id = $1
`

type GetDeliveryTaskRow struct {
	ID                   uuid.UUID        `json:"id"`
	OrderID              uuid.UUID        `json:"order_id"`
	GoodID               uuid.UUID        `json:"good_id"`
	LockerCellID         pgtype.UUID      `json:"locker_cell_id"`
	ParcelAutomatID      uuid.UUID        `json:"parcel_automat_id"`
	InternalLockerCellID pgtype.UUID      `json:"internal_locker_cell_id"`
	Status               string           `json:"status"`
	StartedAt            pgtype.Timestamp `json:"started_at"`
	CompletedAt          pgtype.Timestamp `json:"completed_at"`
	DroneID              pgtype.UUID      `json:"drone_id"`
}

func (q *Queries) GetDeliveryTask(ctx context.Context, id uuid.UUID) (GetDeliveryTaskRow, error) {
	row := q.db.QueryRow(ctx, getDeliveryTask, id)
	var i GetDeliveryTaskRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.GoodID,
		&i.LockerCellID,
		&i.ParcelAutomatID,
		&i.InternalLockerCellID,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.DroneID,
	)
	return i, err
}

const saveDeliveryTask = `-- name: SaveDeliveryTask :exec
UPDATE deliveries
SET 
    drone_id = $2,
    status = $3,
    started_at = COALESCE(started_at, CURRENT_TIMESTAMP)
WHERE id = $1
`

type SaveDeliveryTaskParams struct {
	ID      uuid.UUID   `json:"id"`
	DroneID pgtype.UUID `json:"drone_id"`
	Status  string      `json:"status"`
}

func (q *Queries) SaveDeliveryTask(ctx context.Context, arg SaveDeliveryTaskParams) error {
	_, err := q.db.Exec(ctx, saveDeliveryTask, arg.ID, arg.DroneID, arg.Status)
	return err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE deliveries
SET 
    status = $2,
    completed_at = CASE 
        WHEN $2 = 'completed' THEN CURRENT_TIMESTAMP 
        ELSE completed_at 
    END
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	return err
}
