// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drone.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDroneIDByIP = `-- name: GetDroneIDByIP :one
SELECT id FROM drones
WHERE ip_address = $1
`

func (q *Queries) GetDroneIDByIP(ctx context.Context, ipAddress string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDroneIDByIP, ipAddress)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getDroneState = `-- name: GetDroneState :one
SELECT id, status, battery_level
FROM drones
WHERE id = $1
`

type GetDroneStateRow struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	BatteryLevel pgtype.Numeric `json:"battery_level"`
}

func (q *Queries) GetDroneState(ctx context.Context, id uuid.UUID) (GetDroneStateRow, error) {
	row := q.db.QueryRow(ctx, getDroneState, id)
	var i GetDroneStateRow
	err := row.Scan(&i.ID, &i.Status, &i.BatteryLevel)
	return i, err
}

const saveDroneState = `-- name: SaveDroneState :exec
UPDATE drones
SET 
    status = $2,
    battery_level = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SaveDroneStateParams struct {
	ID           uuid.UUID      `json:"id"`
	Status       string         `json:"status"`
	BatteryLevel pgtype.Numeric `json:"battery_level"`
}

func (q *Queries) SaveDroneState(ctx context.Context, arg SaveDroneStateParams) error {
	_, err := q.db.Exec(ctx, saveDroneState, arg.ID, arg.Status, arg.BatteryLevel)
	return err
}

const updateDroneBattery = `-- name: UpdateDroneBattery :exec
UPDATE drones
SET battery_level = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateDroneBatteryParams struct {
	ID           uuid.UUID      `json:"id"`
	BatteryLevel pgtype.Numeric `json:"battery_level"`
}

func (q *Queries) UpdateDroneBattery(ctx context.Context, arg UpdateDroneBatteryParams) error {
	_, err := q.db.Exec(ctx, updateDroneBattery, arg.ID, arg.BatteryLevel)
	return err
}
