// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeliveryRepo creates a new instance of MockDeliveryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryRepo {
	mock := &MockDeliveryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryRepo is an autogenerated mock type for the DeliveryRepo type
type MockDeliveryRepo struct {
	mock.Mock
}

type MockDeliveryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryRepo) EXPECT() *MockDeliveryRepo_Expecter {
	return &MockDeliveryRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) Create(ctx context.Context, orderID uuid.UUID, droneID *uuid.UUID, parcelAutomatID uuid.UUID, internalLockerCellID *uuid.UUID, status string) (*entity.Delivery, error) {
	ret := _mock.Called(ctx, orderID, droneID, parcelAutomatID, internalLockerCellID, status)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, uuid.UUID, *uuid.UUID, string) (*entity.Delivery, error)); ok {
		return returnFunc(ctx, orderID, droneID, parcelAutomatID, internalLockerCellID, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID, uuid.UUID, *uuid.UUID, string) *entity.Delivery); ok {
		r0 = returnFunc(ctx, orderID, droneID, parcelAutomatID, internalLockerCellID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *uuid.UUID, uuid.UUID, *uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, orderID, droneID, parcelAutomatID, internalLockerCellID, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeliveryRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - droneID *uuid.UUID
//   - parcelAutomatID uuid.UUID
//   - internalLockerCellID *uuid.UUID
//   - status string
func (_e *MockDeliveryRepo_Expecter) Create(ctx interface{}, orderID interface{}, droneID interface{}, parcelAutomatID interface{}, internalLockerCellID interface{}, status interface{}) *MockDeliveryRepo_Create_Call {
	return &MockDeliveryRepo_Create_Call{Call: _e.mock.On("Create", ctx, orderID, droneID, parcelAutomatID, internalLockerCellID, status)}
}

func (_c *MockDeliveryRepo_Create_Call) Run(run func(ctx context.Context, orderID uuid.UUID, droneID *uuid.UUID, parcelAutomatID uuid.UUID, internalLockerCellID *uuid.UUID, status string)) *MockDeliveryRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(*uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 *uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(*uuid.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_Create_Call) Return(delivery *entity.Delivery, err error) *MockDeliveryRepo_Create_Call {
	_c.Call.Return(delivery, err)
	return _c
}

func (_c *MockDeliveryRepo_Create_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, droneID *uuid.UUID, parcelAutomatID uuid.UUID, internalLockerCellID *uuid.UUID, status string) (*entity.Delivery, error)) *MockDeliveryRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.Delivery, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Delivery, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Delivery); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeliveryRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeliveryRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockDeliveryRepo_GetByID_Call {
	return &MockDeliveryRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDeliveryRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeliveryRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_GetByID_Call) Return(delivery *entity.Delivery, err error) *MockDeliveryRepo_GetByID_Call {
	_c.Call.Return(delivery, err)
	return _c
}

func (_c *MockDeliveryRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Delivery, error)) *MockDeliveryRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByOrderID provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) GetByOrderID(ctx context.Context, orderID uuid.UUID) (*entity.Delivery, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByOrderID")
	}

	var r0 *entity.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Delivery, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Delivery); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_GetByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByOrderID'
type MockDeliveryRepo_GetByOrderID_Call struct {
	*mock.Call
}

// GetByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockDeliveryRepo_Expecter) GetByOrderID(ctx interface{}, orderID interface{}) *MockDeliveryRepo_GetByOrderID_Call {
	return &MockDeliveryRepo_GetByOrderID_Call{Call: _e.mock.On("GetByOrderID", ctx, orderID)}
}

func (_c *MockDeliveryRepo_GetByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockDeliveryRepo_GetByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_GetByOrderID_Call) Return(delivery *entity.Delivery, err error) *MockDeliveryRepo_GetByOrderID_Call {
	_c.Call.Return(delivery, err)
	return _c
}

func (_c *MockDeliveryRepo_GetByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (*entity.Delivery, error)) *MockDeliveryRepo_GetByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStatus provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) ListByStatus(ctx context.Context, status string) ([]*entity.Delivery, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for ListByStatus")
	}

	var r0 []*entity.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*entity.Delivery, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*entity.Delivery); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_ListByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStatus'
type MockDeliveryRepo_ListByStatus_Call struct {
	*mock.Call
}

// ListByStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
func (_e *MockDeliveryRepo_Expecter) ListByStatus(ctx interface{}, status interface{}) *MockDeliveryRepo_ListByStatus_Call {
	return &MockDeliveryRepo_ListByStatus_Call{Call: _e.mock.On("ListByStatus", ctx, status)}
}

func (_c *MockDeliveryRepo_ListByStatus_Call) Run(run func(ctx context.Context, status string)) *MockDeliveryRepo_ListByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_ListByStatus_Call) Return(deliverys []*entity.Delivery, err error) *MockDeliveryRepo_ListByStatus_Call {
	_c.Call.Return(deliverys, err)
	return _c
}

func (_c *MockDeliveryRepo_ListByStatus_Call) RunAndReturn(run func(ctx context.Context, status string) ([]*entity.Delivery, error)) *MockDeliveryRepo_ListByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDrone provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) UpdateDrone(ctx context.Context, id uuid.UUID, droneID uuid.UUID) error {
	ret := _mock.Called(ctx, id, droneID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDrone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, droneID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryRepo_UpdateDrone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDrone'
type MockDeliveryRepo_UpdateDrone_Call struct {
	*mock.Call
}

// UpdateDrone is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - droneID uuid.UUID
func (_e *MockDeliveryRepo_Expecter) UpdateDrone(ctx interface{}, id interface{}, droneID interface{}) *MockDeliveryRepo_UpdateDrone_Call {
	return &MockDeliveryRepo_UpdateDrone_Call{Call: _e.mock.On("UpdateDrone", ctx, id, droneID)}
}

func (_c *MockDeliveryRepo_UpdateDrone_Call) Run(run func(ctx context.Context, id uuid.UUID, droneID uuid.UUID)) *MockDeliveryRepo_UpdateDrone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_UpdateDrone_Call) Return(err error) *MockDeliveryRepo_UpdateDrone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryRepo_UpdateDrone_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, droneID uuid.UUID) error) *MockDeliveryRepo_UpdateDrone_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status string) (*entity.Delivery, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *entity.Delivery
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entity.Delivery, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entity.Delivery); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Delivery)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockDeliveryRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockDeliveryRepo_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockDeliveryRepo_UpdateStatus_Call {
	return &MockDeliveryRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockDeliveryRepo_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockDeliveryRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_UpdateStatus_Call) Return(delivery *entity.Delivery, err error) *MockDeliveryRepo_UpdateStatus_Call {
	_c.Call.Return(delivery, err)
	return _c
}

func (_c *MockDeliveryRepo_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status string) (*entity.Delivery, error)) *MockDeliveryRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
