// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceRepo creates a new instance of MockDeviceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepo {
	mock := &MockDeviceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceRepo is an autogenerated mock type for the DeviceRepo type
type MockDeviceRepo struct {
	mock.Mock
}

type MockDeviceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepo) EXPECT() *MockDeviceRepo_Expecter {
	return &MockDeviceRepo_Expecter{mock: &_m.Mock}
}

// DeleteByToken provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) DeleteByToken(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceRepo_DeleteByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByToken'
type MockDeviceRepo_DeleteByToken_Call struct {
	*mock.Call
}

// DeleteByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockDeviceRepo_Expecter) DeleteByToken(ctx interface{}, token interface{}) *MockDeviceRepo_DeleteByToken_Call {
	return &MockDeviceRepo_DeleteByToken_Call{Call: _e.mock.On("DeleteByToken", ctx, token)}
}

func (_c *MockDeviceRepo_DeleteByToken_Call) Run(run func(ctx context.Context, token string)) *MockDeviceRepo_DeleteByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_DeleteByToken_Call) Return(err error) *MockDeviceRepo_DeleteByToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceRepo_DeleteByToken_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockDeviceRepo_DeleteByToken_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.Device, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*entity.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Device, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Device); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Device)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceRepo_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockDeviceRepo_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockDeviceRepo_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockDeviceRepo_ListByUserID_Call {
	return &MockDeviceRepo_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockDeviceRepo_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockDeviceRepo_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_ListByUserID_Call) Return(devices []*entity.Device, err error) *MockDeviceRepo_ListByUserID_Call {
	_c.Call.Return(devices, err)
	return _c
}

func (_c *MockDeviceRepo_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Device, error)) *MockDeviceRepo_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockDeviceRepo
func (_mock *MockDeviceRepo) Upsert(ctx context.Context, device *entity.Device) error {
	ret := _mock.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Device) error); ok {
		r0 = returnFunc(ctx, device)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeviceRepo_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockDeviceRepo_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - device *entity.Device
func (_e *MockDeviceRepo_Expecter) Upsert(ctx interface{}, device interface{}) *MockDeviceRepo_Upsert_Call {
	return &MockDeviceRepo_Upsert_Call{Call: _e.mock.On("Upsert", ctx, device)}
}

func (_c *MockDeviceRepo_Upsert_Call) Run(run func(ctx context.Context, device *entity.Device)) *MockDeviceRepo_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Device
		if args[1] != nil {
			arg1 = args[1].(*entity.Device)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeviceRepo_Upsert_Call) Return(err error) *MockDeviceRepo_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeviceRepo_Upsert_Call) RunAndReturn(run func(ctx context.Context, device *entity.Device) error) *MockDeviceRepo_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
