// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDroneRepo creates a new instance of MockDroneRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDroneRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDroneRepo {
	mock := &MockDroneRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDroneRepo is an autogenerated mock type for the DroneRepo type
type MockDroneRepo struct {
	mock.Mock
}

type MockDroneRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDroneRepo) EXPECT() *MockDroneRepo_Expecter {
	return &MockDroneRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) Create(ctx context.Context, model string, status string, ipAddress string) (*entity.Drone, error) {
	ret := _mock.Called(ctx, model, status, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Drone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*entity.Drone, error)); ok {
		return returnFunc(ctx, model, status, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *entity.Drone); ok {
		r0 = returnFunc(ctx, model, status, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Drone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, model, status, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDroneRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - model string
//   - status string
//   - ipAddress string
func (_e *MockDroneRepo_Expecter) Create(ctx interface{}, model interface{}, status interface{}, ipAddress interface{}) *MockDroneRepo_Create_Call {
	return &MockDroneRepo_Create_Call{Call: _e.mock.On("Create", ctx, model, status, ipAddress)}
}

func (_c *MockDroneRepo_Create_Call) Run(run func(ctx context.Context, model string, status string, ipAddress string)) *MockDroneRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDroneRepo_Create_Call) Return(drone *entity.Drone, err error) *MockDroneRepo_Create_Call {
	_c.Call.Return(drone, err)
	return _c
}

func (_c *MockDroneRepo_Create_Call) RunAndReturn(run func(ctx context.Context, model string, status string, ipAddress string) (*entity.Drone, error)) *MockDroneRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDroneRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDroneRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDroneRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockDroneRepo_Delete_Call {
	return &MockDroneRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDroneRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDroneRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDroneRepo_Delete_Call) Return(err error) *MockDroneRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDroneRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockDroneRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAvailable provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) GetAvailable(ctx context.Context) (*entity.Drone, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailable")
	}

	var r0 *entity.Drone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*entity.Drone, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *entity.Drone); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Drone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_GetAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAvailable'
type MockDroneRepo_GetAvailable_Call struct {
	*mock.Call
}

// GetAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDroneRepo_Expecter) GetAvailable(ctx interface{}) *MockDroneRepo_GetAvailable_Call {
	return &MockDroneRepo_GetAvailable_Call{Call: _e.mock.On("GetAvailable", ctx)}
}

func (_c *MockDroneRepo_GetAvailable_Call) Run(run func(ctx context.Context)) *MockDroneRepo_GetAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDroneRepo_GetAvailable_Call) Return(drone *entity.Drone, err error) *MockDroneRepo_GetAvailable_Call {
	_c.Call.Return(drone, err)
	return _c
}

func (_c *MockDroneRepo_GetAvailable_Call) RunAndReturn(run func(ctx context.Context) (*entity.Drone, error)) *MockDroneRepo_GetAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.Drone, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Drone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Drone, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Drone); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Drone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDroneRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDroneRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockDroneRepo_GetByID_Call {
	return &MockDroneRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDroneRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDroneRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDroneRepo_GetByID_Call) Return(drone *entity.Drone, err error) *MockDroneRepo_GetByID_Call {
	_c.Call.Return(drone, err)
	return _c
}

func (_c *MockDroneRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Drone, error)) *MockDroneRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) List(ctx context.Context) ([]*entity.Drone, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Drone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Drone, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Drone); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Drone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDroneRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDroneRepo_Expecter) List(ctx interface{}) *MockDroneRepo_List_Call {
	return &MockDroneRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDroneRepo_List_Call) Run(run func(ctx context.Context)) *MockDroneRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDroneRepo_List_Call) Return(drones []*entity.Drone, err error) *MockDroneRepo_List_Call {
	_c.Call.Return(drones, err)
	return _c
}

func (_c *MockDroneRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Drone, error)) *MockDroneRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) Update(ctx context.Context, id uuid.UUID, model string, ipAddress string) (*entity.Drone, error) {
	ret := _mock.Called(ctx, id, model, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Drone
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (*entity.Drone, error)); ok {
		return returnFunc(ctx, id, model, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) *entity.Drone); ok {
		r0 = returnFunc(ctx, id, model, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Drone)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, id, model, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDroneRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - model string
//   - ipAddress string
func (_e *MockDroneRepo_Expecter) Update(ctx interface{}, id interface{}, model interface{}, ipAddress interface{}) *MockDroneRepo_Update_Call {
	return &MockDroneRepo_Update_Call{Call: _e.mock.On("Update", ctx, id, model, ipAddress)}
}

func (_c *MockDroneRepo_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, model string, ipAddress string)) *MockDroneRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDroneRepo_Update_Call) Return(drone *entity.Drone, err error) *MockDroneRepo_Update_Call {
	_c.Call.Return(drone, err)
	return _c
}

func (_c *MockDroneRepo_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, model string, ipAddress string) (*entity.Drone, error)) *MockDroneRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) UpdateStatus(ctx context.Context, id uuid.UUID, status string) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDroneRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockDroneRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status string
func (_e *MockDroneRepo_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockDroneRepo_UpdateStatus_Call {
	return &MockDroneRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockDroneRepo_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status string)) *MockDroneRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDroneRepo_UpdateStatus_Call) Return(err error) *MockDroneRepo_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDroneRepo_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status string) error) *MockDroneRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
