// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGoodRepo creates a new instance of MockGoodRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGoodRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGoodRepo {
	mock := &MockGoodRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGoodRepo is an autogenerated mock type for the GoodRepo type
type MockGoodRepo struct {
	mock.Mock
}

type MockGoodRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGoodRepo) EXPECT() *MockGoodRepo_Expecter {
	return &MockGoodRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) Create(ctx context.Context, good *entity.Good) (*entity.Good, error) {
	ret := _mock.Called(ctx, good)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Good) (*entity.Good, error)); ok {
		return returnFunc(ctx, good)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Good) *entity.Good); ok {
		r0 = returnFunc(ctx, good)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Good) error); ok {
		r1 = returnFunc(ctx, good)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGoodRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - good *entity.Good
func (_e *MockGoodRepo_Expecter) Create(ctx interface{}, good interface{}) *MockGoodRepo_Create_Call {
	return &MockGoodRepo_Create_Call{Call: _e.mock.On("Create", ctx, good)}
}

func (_c *MockGoodRepo_Create_Call) Run(run func(ctx context.Context, good *entity.Good)) *MockGoodRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Good
		if args[1] != nil {
			arg1 = args[1].(*entity.Good)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodRepo_Create_Call) Return(good1 *entity.Good, err error) *MockGoodRepo_Create_Call {
	_c.Call.Return(good1, err)
	return _c
}

func (_c *MockGoodRepo_Create_Call) RunAndReturn(run func(ctx context.Context, good *entity.Good) (*entity.Good, error)) *MockGoodRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGoodRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockGoodRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGoodRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockGoodRepo_Delete_Call {
	return &MockGoodRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockGoodRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGoodRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodRepo_Delete_Call) Return(err error) *MockGoodRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGoodRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockGoodRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.Good, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Good, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Good); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockGoodRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockGoodRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockGoodRepo_GetByID_Call {
	return &MockGoodRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockGoodRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockGoodRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodRepo_GetByID_Call) Return(good *entity.Good, err error) *MockGoodRepo_GetByID_Call {
	_c.Call.Return(good, err)
	return _c
}

func (_c *MockGoodRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Good, error)) *MockGoodRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) List(ctx context.Context) ([]*entity.Good, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Good, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Good); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockGoodRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoodRepo_Expecter) List(ctx interface{}) *MockGoodRepo_List_Call {
	return &MockGoodRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockGoodRepo_List_Call) Run(run func(ctx context.Context)) *MockGoodRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGoodRepo_List_Call) Return(goods []*entity.Good, err error) *MockGoodRepo_List_Call {
	_c.Call.Return(goods, err)
	return _c
}

func (_c *MockGoodRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Good, error)) *MockGoodRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListAvailable provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) ListAvailable(ctx context.Context) ([]*entity.Good, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListAvailable")
	}

	var r0 []*entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.Good, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.Good); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_ListAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAvailable'
type MockGoodRepo_ListAvailable_Call struct {
	*mock.Call
}

// ListAvailable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGoodRepo_Expecter) ListAvailable(ctx interface{}) *MockGoodRepo_ListAvailable_Call {
	return &MockGoodRepo_ListAvailable_Call{Call: _e.mock.On("ListAvailable", ctx)}
}

func (_c *MockGoodRepo_ListAvailable_Call) Run(run func(ctx context.Context)) *MockGoodRepo_ListAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGoodRepo_ListAvailable_Call) Return(goods []*entity.Good, err error) *MockGoodRepo_ListAvailable_Call {
	_c.Call.Return(goods, err)
	return _c
}

func (_c *MockGoodRepo_ListAvailable_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.Good, error)) *MockGoodRepo_ListAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) Update(ctx context.Context, good *entity.Good) (*entity.Good, error) {
	ret := _mock.Called(ctx, good)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Good) (*entity.Good, error)); ok {
		return returnFunc(ctx, good)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Good) *entity.Good); ok {
		r0 = returnFunc(ctx, good)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Good) error); ok {
		r1 = returnFunc(ctx, good)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockGoodRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - good *entity.Good
func (_e *MockGoodRepo_Expecter) Update(ctx interface{}, good interface{}) *MockGoodRepo_Update_Call {
	return &MockGoodRepo_Update_Call{Call: _e.mock.On("Update", ctx, good)}
}

func (_c *MockGoodRepo_Update_Call) Run(run func(ctx context.Context, good *entity.Good)) *MockGoodRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Good
		if args[1] != nil {
			arg1 = args[1].(*entity.Good)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGoodRepo_Update_Call) Return(good1 *entity.Good, err error) *MockGoodRepo_Update_Call {
	_c.Call.Return(good1, err)
	return _c
}

func (_c *MockGoodRepo_Update_Call) RunAndReturn(run func(ctx context.Context, good *entity.Good) (*entity.Good, error)) *MockGoodRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQuantity provides a mock function for the type MockGoodRepo
func (_mock *MockGoodRepo) UpdateQuantity(ctx context.Context, id uuid.UUID, delta int) (*entity.Good, error) {
	ret := _mock.Called(ctx, id, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 *entity.Good
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) (*entity.Good, error)); ok {
		return returnFunc(ctx, id, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) *entity.Good); ok {
		r0 = returnFunc(ctx, id, delta)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Good)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, id, delta)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGoodRepo_UpdateQuantity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQuantity'
type MockGoodRepo_UpdateQuantity_Call struct {
	*mock.Call
}

// UpdateQuantity is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - delta int
func (_e *MockGoodRepo_Expecter) UpdateQuantity(ctx interface{}, id interface{}, delta interface{}) *MockGoodRepo_UpdateQuantity_Call {
	return &MockGoodRepo_UpdateQuantity_Call{Call: _e.mock.On("UpdateQuantity", ctx, id, delta)}
}

func (_c *MockGoodRepo_UpdateQuantity_Call) Run(run func(ctx context.Context, id uuid.UUID, delta int)) *MockGoodRepo_UpdateQuantity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGoodRepo_UpdateQuantity_Call) Return(good *entity.Good, err error) *MockGoodRepo_UpdateQuantity_Call {
	_c.Call.Return(good, err)
	return _c
}

func (_c *MockGoodRepo_UpdateQuantity_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, delta int) (*entity.Good, error)) *MockGoodRepo_UpdateQuantity_Call {
	_c.Call.Return(run)
	return _c
}
