// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInternalLockerRepo creates a new instance of MockInternalLockerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInternalLockerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInternalLockerRepo {
	mock := &MockInternalLockerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInternalLockerRepo is an autogenerated mock type for the InternalLockerRepo type
type MockInternalLockerRepo struct {
	mock.Mock
}

type MockInternalLockerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInternalLockerRepo) EXPECT() *MockInternalLockerRepo_Expecter {
	return &MockInternalLockerRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) Create(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, cell)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, cell)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, cell)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.LockerCell) error); ok {
		r1 = returnFunc(ctx, cell)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInternalLockerRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cell *entity.LockerCell
func (_e *MockInternalLockerRepo_Expecter) Create(ctx interface{}, cell interface{}) *MockInternalLockerRepo_Create_Call {
	return &MockInternalLockerRepo_Create_Call{Call: _e.mock.On("Create", ctx, cell)}
}

func (_c *MockInternalLockerRepo_Create_Call) Run(run func(ctx context.Context, cell *entity.LockerCell)) *MockInternalLockerRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LockerCell
		if args[1] != nil {
			arg1 = args[1].(*entity.LockerCell)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_Create_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_Create_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_Create_Call) RunAndReturn(run func(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error)) *MockInternalLockerRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCell provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) CreateCell(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, cell)

	if len(ret) == 0 {
		panic("no return value specified for CreateCell")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, cell)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, cell)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.LockerCell) error); ok {
		r1 = returnFunc(ctx, cell)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_CreateCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCell'
type MockInternalLockerRepo_CreateCell_Call struct {
	*mock.Call
}

// CreateCell is a helper method to define mock.On call
//   - ctx context.Context
//   - cell *entity.LockerCell
func (_e *MockInternalLockerRepo_Expecter) CreateCell(ctx interface{}, cell interface{}) *MockInternalLockerRepo_CreateCell_Call {
	return &MockInternalLockerRepo_CreateCell_Call{Call: _e.mock.On("CreateCell", ctx, cell)}
}

func (_c *MockInternalLockerRepo_CreateCell_Call) Run(run func(ctx context.Context, cell *entity.LockerCell)) *MockInternalLockerRepo_CreateCell_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LockerCell
		if args[1] != nil {
			arg1 = args[1].(*entity.LockerCell)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_CreateCell_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_CreateCell_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_CreateCell_Call) RunAndReturn(run func(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error)) *MockInternalLockerRepo_CreateCell_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithNumber provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) CreateWithNumber(ctx context.Context, cell *entity.LockerCell, cellNumber int) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, cell, cellNumber)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithNumber")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell, int) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, cell, cellNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell, int) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, cell, cellNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.LockerCell, int) error); ok {
		r1 = returnFunc(ctx, cell, cellNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_CreateWithNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithNumber'
type MockInternalLockerRepo_CreateWithNumber_Call struct {
	*mock.Call
}

// CreateWithNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - cell *entity.LockerCell
//   - cellNumber int
func (_e *MockInternalLockerRepo_Expecter) CreateWithNumber(ctx interface{}, cell interface{}, cellNumber interface{}) *MockInternalLockerRepo_CreateWithNumber_Call {
	return &MockInternalLockerRepo_CreateWithNumber_Call{Call: _e.mock.On("CreateWithNumber", ctx, cell, cellNumber)}
}

func (_c *MockInternalLockerRepo_CreateWithNumber_Call) Run(run func(ctx context.Context, cell *entity.LockerCell, cellNumber int)) *MockInternalLockerRepo_CreateWithNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LockerCell
		if args[1] != nil {
			arg1 = args[1].(*entity.LockerCell)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_CreateWithNumber_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_CreateWithNumber_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_CreateWithNumber_Call) RunAndReturn(run func(ctx context.Context, cell *entity.LockerCell, cellNumber int) (*entity.LockerCell, error)) *MockInternalLockerRepo_CreateWithNumber_Call {
	_c.Call.Return(run)
	return _c
}

// FindAvailableCell provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) FindAvailableCell(ctx context.Context, height float64, length float64, width float64) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, height, length, width)

	if len(ret) == 0 {
		panic("no return value specified for FindAvailableCell")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, float64, float64, float64) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, height, length, width)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, float64, float64, float64) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, height, length, width)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, float64, float64, float64) error); ok {
		r1 = returnFunc(ctx, height, length, width)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_FindAvailableCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAvailableCell'
type MockInternalLockerRepo_FindAvailableCell_Call struct {
	*mock.Call
}

// FindAvailableCell is a helper method to define mock.On call
//   - ctx context.Context
//   - height float64
//   - length float64
//   - width float64
func (_e *MockInternalLockerRepo_Expecter) FindAvailableCell(ctx interface{}, height interface{}, length interface{}, width interface{}) *MockInternalLockerRepo_FindAvailableCell_Call {
	return &MockInternalLockerRepo_FindAvailableCell_Call{Call: _e.mock.On("FindAvailableCell", ctx, height, length, width)}
}

func (_c *MockInternalLockerRepo_FindAvailableCell_Call) Run(run func(ctx context.Context, height float64, length float64, width float64)) *MockInternalLockerRepo_FindAvailableCell_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 float64
		if args[1] != nil {
			arg1 = args[1].(float64)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_FindAvailableCell_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_FindAvailableCell_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_FindAvailableCell_Call) RunAndReturn(run func(ctx context.Context, height float64, length float64, width float64) (*entity.LockerCell, error)) *MockInternalLockerRepo_FindAvailableCell_Call {
	_c.Call.Return(run)
	return _c
}

// GetCellByID provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) GetCellByID(ctx context.Context, id uuid.UUID) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCellByID")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_GetCellByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCellByID'
type MockInternalLockerRepo_GetCellByID_Call struct {
	*mock.Call
}

// GetCellByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockInternalLockerRepo_Expecter) GetCellByID(ctx interface{}, id interface{}) *MockInternalLockerRepo_GetCellByID_Call {
	return &MockInternalLockerRepo_GetCellByID_Call{Call: _e.mock.On("GetCellByID", ctx, id)}
}

func (_c *MockInternalLockerRepo_GetCellByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockInternalLockerRepo_GetCellByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_GetCellByID_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_GetCellByID_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_GetCellByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.LockerCell, error)) *MockInternalLockerRepo_GetCellByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListCellsByPostID provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) ListCellsByPostID(ctx context.Context, postID uuid.UUID) ([]*entity.LockerCell, error) {
	ret := _mock.Called(ctx, postID)

	if len(ret) == 0 {
		panic("no return value specified for ListCellsByPostID")
	}

	var r0 []*entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.LockerCell, error)); ok {
		return returnFunc(ctx, postID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.LockerCell); ok {
		r0 = returnFunc(ctx, postID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, postID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_ListCellsByPostID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCellsByPostID'
type MockInternalLockerRepo_ListCellsByPostID_Call struct {
	*mock.Call
}

// ListCellsByPostID is a helper method to define mock.On call
//   - ctx context.Context
//   - postID uuid.UUID
func (_e *MockInternalLockerRepo_Expecter) ListCellsByPostID(ctx interface{}, postID interface{}) *MockInternalLockerRepo_ListCellsByPostID_Call {
	return &MockInternalLockerRepo_ListCellsByPostID_Call{Call: _e.mock.On("ListCellsByPostID", ctx, postID)}
}

func (_c *MockInternalLockerRepo_ListCellsByPostID_Call) Run(run func(ctx context.Context, postID uuid.UUID)) *MockInternalLockerRepo_ListCellsByPostID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_ListCellsByPostID_Call) Return(lockerCells []*entity.LockerCell, err error) *MockInternalLockerRepo_ListCellsByPostID_Call {
	_c.Call.Return(lockerCells, err)
	return _c
}

func (_c *MockInternalLockerRepo_ListCellsByPostID_Call) RunAndReturn(run func(ctx context.Context, postID uuid.UUID) ([]*entity.LockerCell, error)) *MockInternalLockerRepo_ListCellsByPostID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCellStatus provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) UpdateCellStatus(ctx context.Context, cell *entity.LockerCell) error {
	ret := _mock.Called(ctx, cell)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCellStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) error); ok {
		r0 = returnFunc(ctx, cell)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInternalLockerRepo_UpdateCellStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCellStatus'
type MockInternalLockerRepo_UpdateCellStatus_Call struct {
	*mock.Call
}

// UpdateCellStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - cell *entity.LockerCell
func (_e *MockInternalLockerRepo_Expecter) UpdateCellStatus(ctx interface{}, cell interface{}) *MockInternalLockerRepo_UpdateCellStatus_Call {
	return &MockInternalLockerRepo_UpdateCellStatus_Call{Call: _e.mock.On("UpdateCellStatus", ctx, cell)}
}

func (_c *MockInternalLockerRepo_UpdateCellStatus_Call) Run(run func(ctx context.Context, cell *entity.LockerCell)) *MockInternalLockerRepo_UpdateCellStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LockerCell
		if args[1] != nil {
			arg1 = args[1].(*entity.LockerCell)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_UpdateCellStatus_Call) Return(err error) *MockInternalLockerRepo_UpdateCellStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInternalLockerRepo_UpdateCellStatus_Call) RunAndReturn(run func(ctx context.Context, cell *entity.LockerCell) error) *MockInternalLockerRepo_UpdateCellStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDimensions provides a mock function for the type MockInternalLockerRepo
func (_mock *MockInternalLockerRepo) UpdateDimensions(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error) {
	ret := _mock.Called(ctx, cell)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDimensions")
	}

	var r0 *entity.LockerCell
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) (*entity.LockerCell, error)); ok {
		return returnFunc(ctx, cell)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.LockerCell) *entity.LockerCell); ok {
		r0 = returnFunc(ctx, cell)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.LockerCell)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.LockerCell) error); ok {
		r1 = returnFunc(ctx, cell)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInternalLockerRepo_UpdateDimensions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDimensions'
type MockInternalLockerRepo_UpdateDimensions_Call struct {
	*mock.Call
}

// UpdateDimensions is a helper method to define mock.On call
//   - ctx context.Context
//   - cell *entity.LockerCell
func (_e *MockInternalLockerRepo_Expecter) UpdateDimensions(ctx interface{}, cell interface{}) *MockInternalLockerRepo_UpdateDimensions_Call {
	return &MockInternalLockerRepo_UpdateDimensions_Call{Call: _e.mock.On("UpdateDimensions", ctx, cell)}
}

func (_c *MockInternalLockerRepo_UpdateDimensions_Call) Run(run func(ctx context.Context, cell *entity.LockerCell)) *MockInternalLockerRepo_UpdateDimensions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.LockerCell
		if args[1] != nil {
			arg1 = args[1].(*entity.LockerCell)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInternalLockerRepo_UpdateDimensions_Call) Return(lockerCell *entity.LockerCell, err error) *MockInternalLockerRepo_UpdateDimensions_Call {
	_c.Call.Return(lockerCell, err)
	return _c
}

func (_c *MockInternalLockerRepo_UpdateDimensions_Call) RunAndReturn(run func(ctx context.Context, cell *entity.LockerCell) (*entity.LockerCell, error)) *MockInternalLockerRepo_UpdateDimensions_Call {
	_c.Call.Return(run)
	return _c
}
