// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Interface type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function for the type MockLogger
func (_mock *MockLogger) Debug(msg string, err error, fields ...map[string]any) {
	if len(fields) > 0 {
		_mock.Called(msg, err, fields)
	} else {
		_mock.Called(msg, err)
	}

	return
}

// MockLogger_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockLogger_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...map[string]any
func (_e *MockLogger_Expecter) Debug(msg interface{}, err interface{}, fields ...interface{}) *MockLogger_Debug_Call {
	return &MockLogger_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockLogger_Debug_Call) Run(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []map[string]any
		var variadicArgs []map[string]any
		if len(args) > 2 {
			variadicArgs = args[2].([]map[string]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Debug_Call) Return() *MockLogger_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Debug_Call) RunAndReturn(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(msg string, err error, fields ...map[string]any) {
	if len(fields) > 0 {
		_mock.Called(msg, err, fields)
	} else {
		_mock.Called(msg, err)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...map[string]any
func (_e *MockLogger_Expecter) Error(msg interface{}, err interface{}, fields ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []map[string]any
		var variadicArgs []map[string]any
		if len(args) > 2 {
			variadicArgs = args[2].([]map[string]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function for the type MockLogger
func (_mock *MockLogger) Fatal(msg string, err error, fields ...map[string]any) {
	if len(fields) > 0 {
		_mock.Called(msg, err, fields)
	} else {
		_mock.Called(msg, err)
	}

	return
}

// MockLogger_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockLogger_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...map[string]any
func (_e *MockLogger_Expecter) Fatal(msg interface{}, err interface{}, fields ...interface{}) *MockLogger_Fatal_Call {
	return &MockLogger_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockLogger_Fatal_Call) Run(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []map[string]any
		var variadicArgs []map[string]any
		if len(args) > 2 {
			variadicArgs = args[2].([]map[string]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Fatal_Call) Return() *MockLogger_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Fatal_Call) RunAndReturn(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, err error, fields ...map[string]any) {
	if len(fields) > 0 {
		_mock.Called(msg, err, fields)
	} else {
		_mock.Called(msg, err)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...map[string]any
func (_e *MockLogger_Expecter) Info(msg interface{}, err interface{}, fields ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []map[string]any
		var variadicArgs []map[string]any
		if len(args) > 2 {
			variadicArgs = args[2].([]map[string]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function for the type MockLogger
func (_mock *MockLogger) Warn(msg string, err error, fields ...map[string]any) {
	if len(fields) > 0 {
		_mock.Called(msg, err, fields)
	} else {
		_mock.Called(msg, err)
	}

	return
}

// MockLogger_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockLogger_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...map[string]any
func (_e *MockLogger_Expecter) Warn(msg interface{}, err interface{}, fields ...interface{}) *MockLogger_Warn_Call {
	return &MockLogger_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockLogger_Warn_Call) Run(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		var arg2 []map[string]any
		var variadicArgs []map[string]any
		if len(args) > 2 {
			variadicArgs = args[2].([]map[string]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Warn_Call) Return() *MockLogger_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Warn_Call) RunAndReturn(run func(msg string, err error, fields ...map[string]any)) *MockLogger_Warn_Call {
	_c.Run(run)
	return _c
}
