// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMinioClient creates a new instance of MockMinioClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMinioClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMinioClient {
	mock := &MockMinioClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMinioClient is an autogenerated mock type for the MinioClient type
type MockMinioClient struct {
	mock.Mock
}

type MockMinioClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMinioClient) EXPECT() *MockMinioClient_Expecter {
	return &MockMinioClient_Expecter{mock: &_m.Mock}
}

// DeleteFile provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) DeleteFile(ctx context.Context, objectName string) error {
	ret := _mock.Called(ctx, objectName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, objectName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinioClient_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockMinioClient_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
func (_e *MockMinioClient_Expecter) DeleteFile(ctx interface{}, objectName interface{}) *MockMinioClient_DeleteFile_Call {
	return &MockMinioClient_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, objectName)}
}

func (_c *MockMinioClient_DeleteFile_Call) Run(run func(ctx context.Context, objectName string)) *MockMinioClient_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMinioClient_DeleteFile_Call) Return(err error) *MockMinioClient_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinioClient_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, objectName string) error) *MockMinioClient_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureBucket provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) EnsureBucket(ctx context.Context, bucketNames ...string) error {
	var tmpRet mock.Arguments
	if len(bucketNames) > 0 {
		tmpRet = _mock.Called(ctx, bucketNames)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EnsureBucket")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, bucketNames...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinioClient_EnsureBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureBucket'
type MockMinioClient_EnsureBucket_Call struct {
	*mock.Call
}

// EnsureBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - bucketNames ...string
func (_e *MockMinioClient_Expecter) EnsureBucket(ctx interface{}, bucketNames ...interface{}) *MockMinioClient_EnsureBucket_Call {
	return &MockMinioClient_EnsureBucket_Call{Call: _e.mock.On("EnsureBucket",
		append([]interface{}{ctx}, bucketNames...)...)}
}

func (_c *MockMinioClient_EnsureBucket_Call) Run(run func(ctx context.Context, bucketNames ...string)) *MockMinioClient_EnsureBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMinioClient_EnsureBucket_Call) Return(err error) *MockMinioClient_EnsureBucket_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinioClient_EnsureBucket_Call) RunAndReturn(run func(ctx context.Context, bucketNames ...string) error) *MockMinioClient_EnsureBucket_Call {
	_c.Call.Return(run)
	return _c
}

// GetFile provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) GetFile(ctx context.Context, objectName string) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, objectName)

	if len(ret) == 0 {
		panic("no return value specified for GetFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, objectName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = returnFunc(ctx, objectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMinioClient_GetFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFile'
type MockMinioClient_GetFile_Call struct {
	*mock.Call
}

// GetFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
func (_e *MockMinioClient_Expecter) GetFile(ctx interface{}, objectName interface{}) *MockMinioClient_GetFile_Call {
	return &MockMinioClient_GetFile_Call{Call: _e.mock.On("GetFile", ctx, objectName)}
}

func (_c *MockMinioClient_GetFile_Call) Run(run func(ctx context.Context, objectName string)) *MockMinioClient_GetFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMinioClient_GetFile_Call) Return(readCloser io.ReadCloser, err error) *MockMinioClient_GetFile_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *MockMinioClient_GetFile_Call) RunAndReturn(run func(ctx context.Context, objectName string) (io.ReadCloser, error)) *MockMinioClient_GetFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileURL provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) GetFileURL(objectName string) string {
	ret := _mock.Called(objectName)

	if len(ret) == 0 {
		panic("no return value specified for GetFileURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(objectName)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMinioClient_GetFileURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileURL'
type MockMinioClient_GetFileURL_Call struct {
	*mock.Call
}

// GetFileURL is a helper method to define mock.On call
//   - objectName string
func (_e *MockMinioClient_Expecter) GetFileURL(objectName interface{}) *MockMinioClient_GetFileURL_Call {
	return &MockMinioClient_GetFileURL_Call{Call: _e.mock.On("GetFileURL", objectName)}
}

func (_c *MockMinioClient_GetFileURL_Call) Run(run func(objectName string)) *MockMinioClient_GetFileURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMinioClient_GetFileURL_Call) Return(s string) *MockMinioClient_GetFileURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMinioClient_GetFileURL_Call) RunAndReturn(run func(objectName string) string) *MockMinioClient_GetFileURL_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockMinioClient
func (_mock *MockMinioClient) UploadFile(ctx context.Context, objectName string, reader io.Reader, objectSize int64, contentType string) error {
	ret := _mock.Called(ctx, objectName, reader, objectSize, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = returnFunc(ctx, objectName, reader, objectSize, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMinioClient_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockMinioClient_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - objectName string
//   - reader io.Reader
//   - objectSize int64
//   - contentType string
func (_e *MockMinioClient_Expecter) UploadFile(ctx interface{}, objectName interface{}, reader interface{}, objectSize interface{}, contentType interface{}) *MockMinioClient_UploadFile_Call {
	return &MockMinioClient_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, objectName, reader, objectSize, contentType)}
}

func (_c *MockMinioClient_UploadFile_Call) Run(run func(ctx context.Context, objectName string, reader io.Reader, objectSize int64, contentType string)) *MockMinioClient_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockMinioClient_UploadFile_Call) Return(err error) *MockMinioClient_UploadFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMinioClient_UploadFile_Call) RunAndReturn(run func(ctx context.Context, objectName string, reader io.Reader, objectSize int64, contentType string) error) *MockMinioClient_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}
