// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrangePIWebAPI creates a new instance of MockOrangePIWebAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrangePIWebAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrangePIWebAPI {
	mock := &MockOrangePIWebAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrangePIWebAPI is an autogenerated mock type for the OrangePIWebAPI type
type MockOrangePIWebAPI struct {
	mock.Mock
}

type MockOrangePIWebAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrangePIWebAPI) EXPECT() *MockOrangePIWebAPI_Expecter {
	return &MockOrangePIWebAPI_Expecter{mock: &_m.Mock}
}

// OpenCell provides a mock function for the type MockOrangePIWebAPI
func (_mock *MockOrangePIWebAPI) OpenCell(ctx context.Context, ipAddress string, cellID uuid.UUID) error {
	ret := _mock.Called(ctx, ipAddress, cellID)

	if len(ret) == 0 {
		panic("no return value specified for OpenCell")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ipAddress, cellID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrangePIWebAPI_OpenCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenCell'
type MockOrangePIWebAPI_OpenCell_Call struct {
	*mock.Call
}

// OpenCell is a helper method to define mock.On call
//   - ctx context.Context
//   - ipAddress string
//   - cellID uuid.UUID
func (_e *MockOrangePIWebAPI_Expecter) OpenCell(ctx interface{}, ipAddress interface{}, cellID interface{}) *MockOrangePIWebAPI_OpenCell_Call {
	return &MockOrangePIWebAPI_OpenCell_Call{Call: _e.mock.On("OpenCell", ctx, ipAddress, cellID)}
}

func (_c *MockOrangePIWebAPI_OpenCell_Call) Run(run func(ctx context.Context, ipAddress string, cellID uuid.UUID)) *MockOrangePIWebAPI_OpenCell_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrangePIWebAPI_OpenCell_Call) Return(err error) *MockOrangePIWebAPI_OpenCell_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrangePIWebAPI_OpenCell_Call) RunAndReturn(run func(ctx context.Context, ipAddress string, cellID uuid.UUID) error) *MockOrangePIWebAPI_OpenCell_Call {
	_c.Call.Return(run)
	return _c
}

// SendCellUUIDs provides a mock function for the type MockOrangePIWebAPI
func (_mock *MockOrangePIWebAPI) SendCellUUIDs(ctx context.Context, ipAddress string, parcelAutomatID uuid.UUID, outCellUUIDs []uuid.UUID, internalCellUUIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, ipAddress, parcelAutomatID, outCellUUIDs, internalCellUUIDs)

	if len(ret) == 0 {
		panic("no return value specified for SendCellUUIDs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, []uuid.UUID, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, ipAddress, parcelAutomatID, outCellUUIDs, internalCellUUIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrangePIWebAPI_SendCellUUIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCellUUIDs'
type MockOrangePIWebAPI_SendCellUUIDs_Call struct {
	*mock.Call
}

// SendCellUUIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ipAddress string
//   - parcelAutomatID uuid.UUID
//   - outCellUUIDs []uuid.UUID
//   - internalCellUUIDs []uuid.UUID
func (_e *MockOrangePIWebAPI_Expecter) SendCellUUIDs(ctx interface{}, ipAddress interface{}, parcelAutomatID interface{}, outCellUUIDs interface{}, internalCellUUIDs interface{}) *MockOrangePIWebAPI_SendCellUUIDs_Call {
	return &MockOrangePIWebAPI_SendCellUUIDs_Call{Call: _e.mock.On("SendCellUUIDs", ctx, ipAddress, parcelAutomatID, outCellUUIDs, internalCellUUIDs)}
}

func (_c *MockOrangePIWebAPI_SendCellUUIDs_Call) Run(run func(ctx context.Context, ipAddress string, parcelAutomatID uuid.UUID, outCellUUIDs []uuid.UUID, internalCellUUIDs []uuid.UUID)) *MockOrangePIWebAPI_SendCellUUIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 []uuid.UUID
		if args[3] != nil {
			arg3 = args[3].([]uuid.UUID)
		}
		var arg4 []uuid.UUID
		if args[4] != nil {
			arg4 = args[4].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrangePIWebAPI_SendCellUUIDs_Call) Return(err error) *MockOrangePIWebAPI_SendCellUUIDs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrangePIWebAPI_SendCellUUIDs_Call) RunAndReturn(run func(ctx context.Context, ipAddress string, parcelAutomatID uuid.UUID, outCellUUIDs []uuid.UUID, internalCellUUIDs []uuid.UUID) error) *MockOrangePIWebAPI_SendCellUUIDs_Call {
	_c.Call.Return(run)
	return _c
}
