// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepo creates a new instance of MockOrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepo {
	mock := &MockOrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepo is an autogenerated mock type for the OrderRepo type
type MockOrderRepo struct {
	mock.Mock
}

type MockOrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepo) EXPECT() *MockOrderRepo_Expecter {
	return &MockOrderRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) Create(ctx context.Context, order *entity.Order) (*entity.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) (*entity.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) *entity.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrderRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
func (_e *MockOrderRepo_Expecter) Create(ctx interface{}, order interface{}) *MockOrderRepo_Create_Call {
	return &MockOrderRepo_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *MockOrderRepo_Create_Call) Run(run func(ctx context.Context, order *entity.Order)) *MockOrderRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_Create_Call) Return(order1 *entity.Order, err error) *MockOrderRepo_Create_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepo_Create_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order) (*entity.Order, error)) *MockOrderRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithCell provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) CreateWithCell(ctx context.Context, order *entity.Order) (*entity.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithCell")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) (*entity.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) *entity.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_CreateWithCell_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithCell'
type MockOrderRepo_CreateWithCell_Call struct {
	*mock.Call
}

// CreateWithCell is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
func (_e *MockOrderRepo_Expecter) CreateWithCell(ctx interface{}, order interface{}) *MockOrderRepo_CreateWithCell_Call {
	return &MockOrderRepo_CreateWithCell_Call{Call: _e.mock.On("CreateWithCell", ctx, order)}
}

func (_c *MockOrderRepo_CreateWithCell_Call) Run(run func(ctx context.Context, order *entity.Order)) *MockOrderRepo_CreateWithCell_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_CreateWithCell_Call) Return(order1 *entity.Order, err error) *MockOrderRepo_CreateWithCell_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepo_CreateWithCell_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order) (*entity.Order, error)) *MockOrderRepo_CreateWithCell_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrderRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrderRepo_GetByID_Call {
	return &MockOrderRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrderRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetByID_Call) Return(order *entity.Order, err error) *MockOrderRepo_GetByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Order, error)) *MockOrderRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByLockerCellID provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) GetByLockerCellID(ctx context.Context, lockerCellID uuid.UUID) (*entity.Order, error) {
	ret := _mock.Called(ctx, lockerCellID)

	if len(ret) == 0 {
		panic("no return value specified for GetByLockerCellID")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Order, error)); ok {
		return returnFunc(ctx, lockerCellID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Order); ok {
		r0 = returnFunc(ctx, lockerCellID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, lockerCellID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_GetByLockerCellID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByLockerCellID'
type MockOrderRepo_GetByLockerCellID_Call struct {
	*mock.Call
}

// GetByLockerCellID is a helper method to define mock.On call
//   - ctx context.Context
//   - lockerCellID uuid.UUID
func (_e *MockOrderRepo_Expecter) GetByLockerCellID(ctx interface{}, lockerCellID interface{}) *MockOrderRepo_GetByLockerCellID_Call {
	return &MockOrderRepo_GetByLockerCellID_Call{Call: _e.mock.On("GetByLockerCellID", ctx, lockerCellID)}
}

func (_c *MockOrderRepo_GetByLockerCellID_Call) Run(run func(ctx context.Context, lockerCellID uuid.UUID)) *MockOrderRepo_GetByLockerCellID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_GetByLockerCellID_Call) Return(order *entity.Order, err error) *MockOrderRepo_GetByLockerCellID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepo_GetByLockerCellID_Call) RunAndReturn(run func(ctx context.Context, lockerCellID uuid.UUID) (*entity.Order, error)) *MockOrderRepo_GetByLockerCellID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) ListByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.Order, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Order, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Order); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockOrderRepo_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOrderRepo_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockOrderRepo_ListByUserID_Call {
	return &MockOrderRepo_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockOrderRepo_ListByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOrderRepo_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_ListByUserID_Call) Return(orders []*entity.Order, err error) *MockOrderRepo_ListByUserID_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepo_ListByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*entity.Order, error)) *MockOrderRepo_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserIDWithGoods provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) ListByUserIDWithGoods(ctx context.Context, userID uuid.UUID) ([]struct {
	Order *entity.Order
	Good  *entity.Good
}, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserIDWithGoods")
	}

	var r0 []struct {
		Order *entity.Order
		Good  *entity.Good
	}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]struct {
		Order *entity.Order
		Good  *entity.Good
	}, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []struct {
		Order *entity.Order
		Good  *entity.Good
	}); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]struct {
				Order *entity.Order
				Good  *entity.Good
			})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_ListByUserIDWithGoods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserIDWithGoods'
type MockOrderRepo_ListByUserIDWithGoods_Call struct {
	*mock.Call
}

// ListByUserIDWithGoods is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockOrderRepo_Expecter) ListByUserIDWithGoods(ctx interface{}, userID interface{}) *MockOrderRepo_ListByUserIDWithGoods_Call {
	return &MockOrderRepo_ListByUserIDWithGoods_Call{Call: _e.mock.On("ListByUserIDWithGoods", ctx, userID)}
}

func (_c *MockOrderRepo_ListByUserIDWithGoods_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockOrderRepo_ListByUserIDWithGoods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_ListByUserIDWithGoods_Call) Return(vals []struct {
	Order *entity.Order
	Good  *entity.Good
}, err error) *MockOrderRepo_ListByUserIDWithGoods_Call {
	_c.Call.Return(vals, err)
	return _c
}

func (_c *MockOrderRepo_ListByUserIDWithGoods_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]struct {
	Order *entity.Order
	Good  *entity.Good
}, error)) *MockOrderRepo_ListByUserIDWithGoods_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockOrderRepo
func (_mock *MockOrderRepo) UpdateStatus(ctx context.Context, order *entity.Order) (*entity.Order, error) {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *entity.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) (*entity.Order, error)); ok {
		return returnFunc(ctx, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Order) *entity.Order); ok {
		r0 = returnFunc(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Order) error); ok {
		r1 = returnFunc(ctx, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockOrderRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - order *entity.Order
func (_e *MockOrderRepo_Expecter) UpdateStatus(ctx interface{}, order interface{}) *MockOrderRepo_UpdateStatus_Call {
	return &MockOrderRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, order)}
}

func (_c *MockOrderRepo_UpdateStatus_Call) Run(run func(ctx context.Context, order *entity.Order)) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Order
		if args[1] != nil {
			arg1 = args[1].(*entity.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepo_UpdateStatus_Call) Return(order1 *entity.Order, err error) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Return(order1, err)
	return _c
}

func (_c *MockOrderRepo_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, order *entity.Order) (*entity.Order, error)) *MockOrderRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
