// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParcelAutomatRepo creates a new instance of MockParcelAutomatRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParcelAutomatRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParcelAutomatRepo {
	mock := &MockParcelAutomatRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParcelAutomatRepo is an autogenerated mock type for the ParcelAutomatRepo type
type MockParcelAutomatRepo struct {
	mock.Mock
}

type MockParcelAutomatRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParcelAutomatRepo) EXPECT() *MockParcelAutomatRepo_Expecter {
	return &MockParcelAutomatRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) Create(ctx context.Context, city string, address string, numberOfCells int, ipAddress string, coordinates string, arucoID int, isWorking bool) (*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx, city, address, numberOfCells, ipAddress, coordinates, arucoID, isWorking)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string, string, int, bool) (*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx, city, address, numberOfCells, ipAddress, coordinates, arucoID, isWorking)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, string, string, int, bool) *entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx, city, address, numberOfCells, ipAddress, coordinates, arucoID, isWorking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, string, string, int, bool) error); ok {
		r1 = returnFunc(ctx, city, address, numberOfCells, ipAddress, coordinates, arucoID, isWorking)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockParcelAutomatRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - city string
//   - address string
//   - numberOfCells int
//   - ipAddress string
//   - coordinates string
//   - arucoID int
//   - isWorking bool
func (_e *MockParcelAutomatRepo_Expecter) Create(ctx interface{}, city interface{}, address interface{}, numberOfCells interface{}, ipAddress interface{}, coordinates interface{}, arucoID interface{}, isWorking interface{}) *MockParcelAutomatRepo_Create_Call {
	return &MockParcelAutomatRepo_Create_Call{Call: _e.mock.On("Create", ctx, city, address, numberOfCells, ipAddress, coordinates, arucoID, isWorking)}
}

func (_c *MockParcelAutomatRepo_Create_Call) Run(run func(ctx context.Context, city string, address string, numberOfCells int, ipAddress string, coordinates string, arucoID int, isWorking bool)) *MockParcelAutomatRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 int
		if args[6] != nil {
			arg6 = args[6].(int)
		}
		var arg7 bool
		if args[7] != nil {
			arg7 = args[7].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_Create_Call) Return(parcelAutomat *entity.ParcelAutomat, err error) *MockParcelAutomatRepo_Create_Call {
	_c.Call.Return(parcelAutomat, err)
	return _c
}

func (_c *MockParcelAutomatRepo_Create_Call) RunAndReturn(run func(ctx context.Context, city string, address string, numberOfCells int, ipAddress string, coordinates string, arucoID int, isWorking bool) (*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParcelAutomatRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockParcelAutomatRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockParcelAutomatRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockParcelAutomatRepo_Delete_Call {
	return &MockParcelAutomatRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockParcelAutomatRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockParcelAutomatRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_Delete_Call) Return(err error) *MockParcelAutomatRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParcelAutomatRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockParcelAutomatRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockParcelAutomatRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockParcelAutomatRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockParcelAutomatRepo_GetByID_Call {
	return &MockParcelAutomatRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockParcelAutomatRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockParcelAutomatRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_GetByID_Call) Return(parcelAutomat *entity.ParcelAutomat, err error) *MockParcelAutomatRepo_GetByID_Call {
	_c.Call.Return(parcelAutomat, err)
	return _c
}

func (_c *MockParcelAutomatRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) List(ctx context.Context) ([]*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockParcelAutomatRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockParcelAutomatRepo_Expecter) List(ctx interface{}) *MockParcelAutomatRepo_List_Call {
	return &MockParcelAutomatRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockParcelAutomatRepo_List_Call) Run(run func(ctx context.Context)) *MockParcelAutomatRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_List_Call) Return(parcelAutomats []*entity.ParcelAutomat, err error) *MockParcelAutomatRepo_List_Call {
	_c.Call.Return(parcelAutomats, err)
	return _c
}

func (_c *MockParcelAutomatRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorking provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) ListWorking(ctx context.Context) ([]*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListWorking")
	}

	var r0 []*entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_ListWorking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorking'
type MockParcelAutomatRepo_ListWorking_Call struct {
	*mock.Call
}

// ListWorking is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockParcelAutomatRepo_Expecter) ListWorking(ctx interface{}) *MockParcelAutomatRepo_ListWorking_Call {
	return &MockParcelAutomatRepo_ListWorking_Call{Call: _e.mock.On("ListWorking", ctx)}
}

func (_c *MockParcelAutomatRepo_ListWorking_Call) Run(run func(ctx context.Context)) *MockParcelAutomatRepo_ListWorking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_ListWorking_Call) Return(parcelAutomats []*entity.ParcelAutomat, err error) *MockParcelAutomatRepo_ListWorking_Call {
	_c.Call.Return(parcelAutomats, err)
	return _c
}

func (_c *MockParcelAutomatRepo_ListWorking_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_ListWorking_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) Update(ctx context.Context, id uuid.UUID, city string, address string, ipAddress string, coordinates string) (*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx, id, city, address, ipAddress, coordinates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string) (*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx, id, city, address, ipAddress, coordinates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string, string) *entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx, id, city, address, ipAddress, coordinates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, city, address, ipAddress, coordinates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockParcelAutomatRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - city string
//   - address string
//   - ipAddress string
//   - coordinates string
func (_e *MockParcelAutomatRepo_Expecter) Update(ctx interface{}, id interface{}, city interface{}, address interface{}, ipAddress interface{}, coordinates interface{}) *MockParcelAutomatRepo_Update_Call {
	return &MockParcelAutomatRepo_Update_Call{Call: _e.mock.On("Update", ctx, id, city, address, ipAddress, coordinates)}
}

func (_c *MockParcelAutomatRepo_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, city string, address string, ipAddress string, coordinates string)) *MockParcelAutomatRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_Update_Call) Return(parcelAutomat *entity.ParcelAutomat, err error) *MockParcelAutomatRepo_Update_Call {
	_c.Call.Return(parcelAutomat, err)
	return _c
}

func (_c *MockParcelAutomatRepo_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, city string, address string, ipAddress string, coordinates string) (*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockParcelAutomatRepo
func (_mock *MockParcelAutomatRepo) UpdateStatus(ctx context.Context, id uuid.UUID, isWorking bool) (*entity.ParcelAutomat, error) {
	ret := _mock.Called(ctx, id, isWorking)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *entity.ParcelAutomat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*entity.ParcelAutomat, error)); ok {
		return returnFunc(ctx, id, isWorking)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *entity.ParcelAutomat); ok {
		r0 = returnFunc(ctx, id, isWorking)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ParcelAutomat)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, isWorking)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParcelAutomatRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockParcelAutomatRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - isWorking bool
func (_e *MockParcelAutomatRepo_Expecter) UpdateStatus(ctx interface{}, id interface{}, isWorking interface{}) *MockParcelAutomatRepo_UpdateStatus_Call {
	return &MockParcelAutomatRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, isWorking)}
}

func (_c *MockParcelAutomatRepo_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, isWorking bool)) *MockParcelAutomatRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParcelAutomatRepo_UpdateStatus_Call) Return(parcelAutomat *entity.ParcelAutomat, err error) *MockParcelAutomatRepo_UpdateStatus_Call {
	_c.Call.Return(parcelAutomat, err)
	return _c
}

func (_c *MockParcelAutomatRepo_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, isWorking bool) (*entity.ParcelAutomat, error)) *MockParcelAutomatRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}
