// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/pkg/qr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQRGenerator creates a new instance of MockQRGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRGenerator {
	mock := &MockQRGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQRGenerator is an autogenerated mock type for the QRGeneratorContract type
type MockQRGenerator struct {
	mock.Mock
}

type MockQRGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRGenerator) EXPECT() *MockQRGenerator_Expecter {
	return &MockQRGenerator_Expecter{mock: &_m.Mock}
}

// GenerateQRCode provides a mock function for the type MockQRGenerator
func (_mock *MockQRGenerator) GenerateQRCode(userID uuid.UUID, email string, name string) (*qr.QRData, string, error) {
	ret := _mock.Called(userID, email, name)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQRCode")
	}

	var r0 *qr.QRData
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string, string) (*qr.QRData, string, error)); ok {
		return returnFunc(userID, email, name)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string, string) *qr.QRData); ok {
		r0 = returnFunc(userID, email, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qr.QRData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string, string) string); ok {
		r1 = returnFunc(userID, email, name)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, string, string) error); ok {
		r2 = returnFunc(userID, email, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQRGenerator_GenerateQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateQRCode'
type MockQRGenerator_GenerateQRCode_Call struct {
	*mock.Call
}

// GenerateQRCode is a helper method to define mock.On call
//   - userID uuid.UUID
//   - email string
//   - name string
func (_e *MockQRGenerator_Expecter) GenerateQRCode(userID interface{}, email interface{}, name interface{}) *MockQRGenerator_GenerateQRCode_Call {
	return &MockQRGenerator_GenerateQRCode_Call{Call: _e.mock.On("GenerateQRCode", userID, email, name)}
}

func (_c *MockQRGenerator_GenerateQRCode_Call) Run(run func(userID uuid.UUID, email string, name string)) *MockQRGenerator_GenerateQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQRGenerator_GenerateQRCode_Call) Return(qrData *qr.QRData, qrImageBase64 string, err error) *MockQRGenerator_GenerateQRCode_Call {
	_c.Call.Return(qrData, qrImageBase64, err)
	return _c
}

func (_c *MockQRGenerator_GenerateQRCode_Call) RunAndReturn(run func(userID uuid.UUID, email string, name string) (*qr.QRData, string, error)) *MockQRGenerator_GenerateQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshQRCode provides a mock function for the type MockQRGenerator
func (_mock *MockQRGenerator) RefreshQRCode(userID uuid.UUID, email string, name string) (*qr.QRData, string, error) {
	ret := _mock.Called(userID, email, name)

	if len(ret) == 0 {
		panic("no return value specified for RefreshQRCode")
	}

	var r0 *qr.QRData
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string, string) (*qr.QRData, string, error)); ok {
		return returnFunc(userID, email, name)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, string, string) *qr.QRData); ok {
		r0 = returnFunc(userID, email, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qr.QRData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, string, string) string); ok {
		r1 = returnFunc(userID, email, name)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uuid.UUID, string, string) error); ok {
		r2 = returnFunc(userID, email, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQRGenerator_RefreshQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshQRCode'
type MockQRGenerator_RefreshQRCode_Call struct {
	*mock.Call
}

// RefreshQRCode is a helper method to define mock.On call
//   - userID uuid.UUID
//   - email string
//   - name string
func (_e *MockQRGenerator_Expecter) RefreshQRCode(userID interface{}, email interface{}, name interface{}) *MockQRGenerator_RefreshQRCode_Call {
	return &MockQRGenerator_RefreshQRCode_Call{Call: _e.mock.On("RefreshQRCode", userID, email, name)}
}

func (_c *MockQRGenerator_RefreshQRCode_Call) Run(run func(userID uuid.UUID, email string, name string)) *MockQRGenerator_RefreshQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQRGenerator_RefreshQRCode_Call) Return(qrData *qr.QRData, qrImageBase64 string, err error) *MockQRGenerator_RefreshQRCode_Call {
	_c.Call.Return(qrData, qrImageBase64, err)
	return _c
}

func (_c *MockQRGenerator_RefreshQRCode_Call) RunAndReturn(run func(userID uuid.UUID, email string, name string) (*qr.QRData, string, error)) *MockQRGenerator_RefreshQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateQRCode provides a mock function for the type MockQRGenerator
func (_mock *MockQRGenerator) ValidateQRCode(qrDataJSON string) (*qr.QRData, error) {
	ret := _mock.Called(qrDataJSON)

	if len(ret) == 0 {
		panic("no return value specified for ValidateQRCode")
	}

	var r0 *qr.QRData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*qr.QRData, error)); ok {
		return returnFunc(qrDataJSON)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *qr.QRData); ok {
		r0 = returnFunc(qrDataJSON)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*qr.QRData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(qrDataJSON)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRGenerator_ValidateQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateQRCode'
type MockQRGenerator_ValidateQRCode_Call struct {
	*mock.Call
}

// ValidateQRCode is a helper method to define mock.On call
//   - qrDataJSON string
func (_e *MockQRGenerator_Expecter) ValidateQRCode(qrDataJSON interface{}) *MockQRGenerator_ValidateQRCode_Call {
	return &MockQRGenerator_ValidateQRCode_Call{Call: _e.mock.On("ValidateQRCode", qrDataJSON)}
}

func (_c *MockQRGenerator_ValidateQRCode_Call) Run(run func(qrDataJSON string)) *MockQRGenerator_ValidateQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQRGenerator_ValidateQRCode_Call) Return(qrData *qr.QRData, err error) *MockQRGenerator_ValidateQRCode_Call {
	_c.Call.Return(qrData, err)
	return _c
}

func (_c *MockQRGenerator_ValidateQRCode_Call) RunAndReturn(run func(qrDataJSON string) (*qr.QRData, error)) *MockQRGenerator_ValidateQRCode_Call {
	_c.Call.Return(run)
	return _c
}
