// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQRWebAPI creates a new instance of MockQRWebAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQRWebAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQRWebAPI {
	mock := &MockQRWebAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQRWebAPI is an autogenerated mock type for the QRWebAPI type
type MockQRWebAPI struct {
	mock.Mock
}

type MockQRWebAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQRWebAPI) EXPECT() *MockQRWebAPI_Expecter {
	return &MockQRWebAPI_Expecter{mock: &_m.Mock}
}

// GenerateQR provides a mock function for the type MockQRWebAPI
func (_mock *MockQRWebAPI) GenerateQR(ctx context.Context, userID uuid.UUID, email string, name string) (string, error) {
	ret := _mock.Called(ctx, userID, email, name)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQR")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (string, error)); ok {
		return returnFunc(ctx, userID, email, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) string); ok {
		r0 = returnFunc(ctx, userID, email, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, userID, email, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQRWebAPI_GenerateQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateQR'
type MockQRWebAPI_GenerateQR_Call struct {
	*mock.Call
}

// GenerateQR is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - email string
//   - name string
func (_e *MockQRWebAPI_Expecter) GenerateQR(ctx interface{}, userID interface{}, email interface{}, name interface{}) *MockQRWebAPI_GenerateQR_Call {
	return &MockQRWebAPI_GenerateQR_Call{Call: _e.mock.On("GenerateQR", ctx, userID, email, name)}
}

func (_c *MockQRWebAPI_GenerateQR_Call) Run(run func(ctx context.Context, userID uuid.UUID, email string, name string)) *MockQRWebAPI_GenerateQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQRWebAPI_GenerateQR_Call) Return(s string, err error) *MockQRWebAPI_GenerateQR_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockQRWebAPI_GenerateQR_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, email string, name string) (string, error)) *MockQRWebAPI_GenerateQR_Call {
	_c.Call.Return(run)
	return _c
}
