// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRabbitMQClient creates a new instance of MockRabbitMQClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRabbitMQClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRabbitMQClient {
	mock := &MockRabbitMQClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRabbitMQClient is an autogenerated mock type for the RabbitMQClient type
type MockRabbitMQClient struct {
	mock.Mock
}

type MockRabbitMQClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRabbitMQClient) EXPECT() *MockRabbitMQClient_Expecter {
	return &MockRabbitMQClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockRabbitMQClient
func (_mock *MockRabbitMQClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRabbitMQClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRabbitMQClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRabbitMQClient_Expecter) Close() *MockRabbitMQClient_Close_Call {
	return &MockRabbitMQClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRabbitMQClient_Close_Call) Run(run func()) *MockRabbitMQClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRabbitMQClient_Close_Call) Return(err error) *MockRabbitMQClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRabbitMQClient_Close_Call) RunAndReturn(run func() error) *MockRabbitMQClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type MockRabbitMQClient
func (_mock *MockRabbitMQClient) Consume(queueName string, handler func([]byte) error) error {
	ret := _mock.Called(queueName, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func([]byte) error) error); ok {
		r0 = returnFunc(queueName, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRabbitMQClient_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockRabbitMQClient_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - queueName string
//   - handler func([]byte) error
func (_e *MockRabbitMQClient_Expecter) Consume(queueName interface{}, handler interface{}) *MockRabbitMQClient_Consume_Call {
	return &MockRabbitMQClient_Consume_Call{Call: _e.mock.On("Consume", queueName, handler)}
}

func (_c *MockRabbitMQClient_Consume_Call) Run(run func(queueName string, handler func([]byte) error)) *MockRabbitMQClient_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func([]byte) error
		if args[1] != nil {
			arg1 = args[1].(func([]byte) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRabbitMQClient_Consume_Call) Return(err error) *MockRabbitMQClient_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRabbitMQClient_Consume_Call) RunAndReturn(run func(queueName string, handler func([]byte) error) error) *MockRabbitMQClient_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockRabbitMQClient
func (_mock *MockRabbitMQClient) Publish(ctx context.Context, queueName string, message any) error {
	ret := _mock.Called(ctx, queueName, message)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = returnFunc(ctx, queueName, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRabbitMQClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockRabbitMQClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - queueName string
//   - message any
func (_e *MockRabbitMQClient_Expecter) Publish(ctx interface{}, queueName interface{}, message interface{}) *MockRabbitMQClient_Publish_Call {
	return &MockRabbitMQClient_Publish_Call{Call: _e.mock.On("Publish", ctx, queueName, message)}
}

func (_c *MockRabbitMQClient_Publish_Call) Run(run func(ctx context.Context, queueName string, message any)) *MockRabbitMQClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRabbitMQClient_Publish_Call) Return(err error) *MockRabbitMQClient_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRabbitMQClient_Publish_Call) RunAndReturn(run func(ctx context.Context, queueName string, message any) error) *MockRabbitMQClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}
