// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// SendDeliveryNotification provides a mock function for the type MockSender
func (_mock *MockSender) SendDeliveryNotification(ctx context.Context, tokens []string, orderID string, lockerCellID *string) ([]string, error) {
	ret := _mock.Called(ctx, tokens, orderID, lockerCellID)

	if len(ret) == 0 {
		panic("no return value specified for SendDeliveryNotification")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, *string) ([]string, error)); ok {
		return returnFunc(ctx, tokens, orderID, lockerCellID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, string, *string) []string); ok {
		r0 = returnFunc(ctx, tokens, orderID, lockerCellID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, string, *string) error); ok {
		r1 = returnFunc(ctx, tokens, orderID, lockerCellID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSender_SendDeliveryNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDeliveryNotification'
type MockSender_SendDeliveryNotification_Call struct {
	*mock.Call
}

// SendDeliveryNotification is a helper method to define mock.On call
//   - ctx context.Context
//   - tokens []string
//   - orderID string
//   - lockerCellID *string
func (_e *MockSender_Expecter) SendDeliveryNotification(ctx interface{}, tokens interface{}, orderID interface{}, lockerCellID interface{}) *MockSender_SendDeliveryNotification_Call {
	return &MockSender_SendDeliveryNotification_Call{Call: _e.mock.On("SendDeliveryNotification", ctx, tokens, orderID, lockerCellID)}
}

func (_c *MockSender_SendDeliveryNotification_Call) Run(run func(ctx context.Context, tokens []string, orderID string, lockerCellID *string)) *MockSender_SendDeliveryNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSender_SendDeliveryNotification_Call) Return(strings []string, err error) *MockSender_SendDeliveryNotification_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSender_SendDeliveryNotification_Call) RunAndReturn(run func(ctx context.Context, tokens []string, orderID string, lockerCellID *string) ([]string, error)) *MockSender_SendDeliveryNotification_Call {
	_c.Call.Return(run)
	return _c
}
