// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSMSAeroWebAPI creates a new instance of MockSMSAeroWebAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMSAeroWebAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMSAeroWebAPI {
	mock := &MockSMSAeroWebAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSMSAeroWebAPI is an autogenerated mock type for the SMSAeroWebAPI type
type MockSMSAeroWebAPI struct {
	mock.Mock
}

type MockSMSAeroWebAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMSAeroWebAPI) EXPECT() *MockSMSAeroWebAPI_Expecter {
	return &MockSMSAeroWebAPI_Expecter{mock: &_m.Mock}
}

// CheckBalance provides a mock function for the type MockSMSAeroWebAPI
func (_mock *MockSMSAeroWebAPI) CheckBalance(ctx context.Context) (float64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckBalance")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (float64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) float64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSMSAeroWebAPI_CheckBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckBalance'
type MockSMSAeroWebAPI_CheckBalance_Call struct {
	*mock.Call
}

// CheckBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSMSAeroWebAPI_Expecter) CheckBalance(ctx interface{}) *MockSMSAeroWebAPI_CheckBalance_Call {
	return &MockSMSAeroWebAPI_CheckBalance_Call{Call: _e.mock.On("CheckBalance", ctx)}
}

func (_c *MockSMSAeroWebAPI_CheckBalance_Call) Run(run func(ctx context.Context)) *MockSMSAeroWebAPI_CheckBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSMSAeroWebAPI_CheckBalance_Call) Return(f float64, err error) *MockSMSAeroWebAPI_CheckBalance_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockSMSAeroWebAPI_CheckBalance_Call) RunAndReturn(run func(ctx context.Context) (float64, error)) *MockSMSAeroWebAPI_CheckBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SendSMS provides a mock function for the type MockSMSAeroWebAPI
func (_mock *MockSMSAeroWebAPI) SendSMS(ctx context.Context, phone string, message string) error {
	ret := _mock.Called(ctx, phone, message)

	if len(ret) == 0 {
		panic("no return value specified for SendSMS")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, phone, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSMSAeroWebAPI_SendSMS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSMS'
type MockSMSAeroWebAPI_SendSMS_Call struct {
	*mock.Call
}

// SendSMS is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
//   - message string
func (_e *MockSMSAeroWebAPI_Expecter) SendSMS(ctx interface{}, phone interface{}, message interface{}) *MockSMSAeroWebAPI_SendSMS_Call {
	return &MockSMSAeroWebAPI_SendSMS_Call{Call: _e.mock.On("SendSMS", ctx, phone, message)}
}

func (_c *MockSMSAeroWebAPI_SendSMS_Call) Run(run func(ctx context.Context, phone string, message string)) *MockSMSAeroWebAPI_SendSMS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSMSAeroWebAPI_SendSMS_Call) Return(err error) *MockSMSAeroWebAPI_SendSMS_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSMSAeroWebAPI_SendSMS_Call) RunAndReturn(run func(ctx context.Context, phone string, message string) error) *MockSMSAeroWebAPI_SendSMS_Call {
	_c.Call.Return(run)
	return _c
}
