// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/skr1ms/SkyPostDelivery/go-orchestrator/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) Create(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepo_Create_Call {
	return &MockUserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepo_Create_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_Create_Call) Return(user1 *entity.User, err error) *MockUserRepo_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *MockUserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithCustomDate provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) CreateWithCustomDate(ctx context.Context, user *entity.User, createdAt time.Time) (*entity.User, error) {
	ret := _mock.Called(ctx, user, createdAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithCustomDate")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User, time.Time) (*entity.User, error)); ok {
		return returnFunc(ctx, user, createdAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User, time.Time) *entity.User); ok {
		r0 = returnFunc(ctx, user, createdAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User, time.Time) error); ok {
		r1 = returnFunc(ctx, user, createdAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_CreateWithCustomDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithCustomDate'
type MockUserRepo_CreateWithCustomDate_Call struct {
	*mock.Call
}

// CreateWithCustomDate is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
//   - createdAt time.Time
func (_e *MockUserRepo_Expecter) CreateWithCustomDate(ctx interface{}, user interface{}, createdAt interface{}) *MockUserRepo_CreateWithCustomDate_Call {
	return &MockUserRepo_CreateWithCustomDate_Call{Call: _e.mock.On("CreateWithCustomDate", ctx, user, createdAt)}
}

func (_c *MockUserRepo_CreateWithCustomDate_Call) Run(run func(ctx context.Context, user *entity.User, createdAt time.Time)) *MockUserRepo_CreateWithCustomDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepo_CreateWithCustomDate_Call) Return(user1 *entity.User, err error) *MockUserRepo_CreateWithCustomDate_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_CreateWithCustomDate_Call) RunAndReturn(run func(ctx context.Context, user *entity.User, createdAt time.Time) (*entity.User, error)) *MockUserRepo_CreateWithCustomDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByEmail(ctx context.Context, email string) (*entity.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type MockUserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepo_Expecter) GetByEmail(ctx interface{}, email interface{}) *MockUserRepo_GetByEmail_Call {
	return &MockUserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *MockUserRepo_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) Return(user *entity.User, err error) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*entity.User, error)) *MockUserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByID(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockUserRepo_GetByID_Call {
	return &MockUserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByID_Call) Return(user *entity.User, err error) *MockUserRepo_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByPhone provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetByPhone(ctx context.Context, phone string) (*entity.User, error) {
	ret := _mock.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhone")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return returnFunc(ctx, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = returnFunc(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByPhone'
type MockUserRepo_GetByPhone_Call struct {
	*mock.Call
}

// GetByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockUserRepo_Expecter) GetByPhone(ctx interface{}, phone interface{}) *MockUserRepo_GetByPhone_Call {
	return &MockUserRepo_GetByPhone_Call{Call: _e.mock.On("GetByPhone", ctx, phone)}
}

func (_c *MockUserRepo_GetByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockUserRepo_GetByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetByPhone_Call) Return(user *entity.User, err error) *MockUserRepo_GetByPhone_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_GetByPhone_Call) RunAndReturn(run func(ctx context.Context, phone string) (*entity.User, error)) *MockUserRepo_GetByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) List(ctx context.Context) ([]*entity.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entity.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entity.User); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepo_Expecter) List(ctx interface{}) *MockUserRepo_List_Call {
	return &MockUserRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockUserRepo_List_Call) Run(run func(ctx context.Context)) *MockUserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepo_List_Call) Return(users []*entity.User, err error) *MockUserRepo_List_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]*entity.User, error)) *MockUserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePassword provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdatePassword(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_UpdatePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePassword'
type MockUserRepo_UpdatePassword_Call struct {
	*mock.Call
}

// UpdatePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) UpdatePassword(ctx interface{}, user interface{}) *MockUserRepo_UpdatePassword_Call {
	return &MockUserRepo_UpdatePassword_Call{Call: _e.mock.On("UpdatePassword", ctx, user)}
}

func (_c *MockUserRepo_UpdatePassword_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdatePassword_Call) Return(user1 *entity.User, err error) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_UpdatePassword_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *MockUserRepo_UpdatePassword_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQR provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateQR(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQR")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_UpdateQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQR'
type MockUserRepo_UpdateQR_Call struct {
	*mock.Call
}

// UpdateQR is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) UpdateQR(ctx interface{}, user interface{}) *MockUserRepo_UpdateQR_Call {
	return &MockUserRepo_UpdateQR_Call{Call: _e.mock.On("UpdateQR", ctx, user)}
}

func (_c *MockUserRepo_UpdateQR_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_UpdateQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateQR_Call) Return(user1 *entity.User, err error) *MockUserRepo_UpdateQR_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_UpdateQR_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *MockUserRepo_UpdateQR_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateVerificationCode provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) UpdateVerificationCode(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVerificationCode")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_UpdateVerificationCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVerificationCode'
type MockUserRepo_UpdateVerificationCode_Call struct {
	*mock.Call
}

// UpdateVerificationCode is a helper method to define mock.On call
//   - ctx context.Context
//   - user *entity.User
func (_e *MockUserRepo_Expecter) UpdateVerificationCode(ctx interface{}, user interface{}) *MockUserRepo_UpdateVerificationCode_Call {
	return &MockUserRepo_UpdateVerificationCode_Call{Call: _e.mock.On("UpdateVerificationCode", ctx, user)}
}

func (_c *MockUserRepo_UpdateVerificationCode_Call) Run(run func(ctx context.Context, user *entity.User)) *MockUserRepo_UpdateVerificationCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.User
		if args[1] != nil {
			arg1 = args[1].(*entity.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_UpdateVerificationCode_Call) Return(user1 *entity.User, err error) *MockUserRepo_UpdateVerificationCode_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepo_UpdateVerificationCode_Call) RunAndReturn(run func(ctx context.Context, user *entity.User) (*entity.User, error)) *MockUserRepo_UpdateVerificationCode_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyPhone provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) VerifyPhone(ctx context.Context, id uuid.UUID) (*entity.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for VerifyPhone")
	}

	var r0 *entity.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_VerifyPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyPhone'
type MockUserRepo_VerifyPhone_Call struct {
	*mock.Call
}

// VerifyPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepo_Expecter) VerifyPhone(ctx interface{}, id interface{}) *MockUserRepo_VerifyPhone_Call {
	return &MockUserRepo_VerifyPhone_Call{Call: _e.mock.On("VerifyPhone", ctx, id)}
}

func (_c *MockUserRepo_VerifyPhone_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepo_VerifyPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_VerifyPhone_Call) Return(user *entity.User, err error) *MockUserRepo_VerifyPhone_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepo_VerifyPhone_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.User, error)) *MockUserRepo_VerifyPhone_Call {
	_c.Call.Return(run)
	return _c
}
