// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/skr1ms/SkyPostDelivery/drone-service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeliveryRepo creates a new instance of MockDeliveryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryRepo {
	mock := &MockDeliveryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryRepo is an autogenerated mock type for the DeliveryRepo type
type MockDeliveryRepo struct {
	mock.Mock
}

type MockDeliveryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryRepo) EXPECT() *MockDeliveryRepo_Expecter {
	return &MockDeliveryRepo_Expecter{mock: &_m.Mock}
}

// GetDeliveryTask provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) GetDeliveryTask(ctx context.Context, deliveryID string) (*entity.DeliveryTask, error) {
	ret := _mock.Called(ctx, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeliveryTask")
	}

	var r0 *entity.DeliveryTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.DeliveryTask, error)); ok {
		return returnFunc(ctx, deliveryID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.DeliveryTask); ok {
		r0 = returnFunc(ctx, deliveryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DeliveryTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, deliveryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRepo_GetDeliveryTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeliveryTask'
type MockDeliveryRepo_GetDeliveryTask_Call struct {
	*mock.Call
}

// GetDeliveryTask is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
func (_e *MockDeliveryRepo_Expecter) GetDeliveryTask(ctx interface{}, deliveryID interface{}) *MockDeliveryRepo_GetDeliveryTask_Call {
	return &MockDeliveryRepo_GetDeliveryTask_Call{Call: _e.mock.On("GetDeliveryTask", ctx, deliveryID)}
}

func (_c *MockDeliveryRepo_GetDeliveryTask_Call) Run(run func(ctx context.Context, deliveryID string)) *MockDeliveryRepo_GetDeliveryTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_GetDeliveryTask_Call) Return(deliveryTask *entity.DeliveryTask, err error) *MockDeliveryRepo_GetDeliveryTask_Call {
	_c.Call.Return(deliveryTask, err)
	return _c
}

func (_c *MockDeliveryRepo_GetDeliveryTask_Call) RunAndReturn(run func(ctx context.Context, deliveryID string) (*entity.DeliveryTask, error)) *MockDeliveryRepo_GetDeliveryTask_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDeliveryTask provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) SaveDeliveryTask(ctx context.Context, task *entity.DeliveryTask) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for SaveDeliveryTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.DeliveryTask) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryRepo_SaveDeliveryTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDeliveryTask'
type MockDeliveryRepo_SaveDeliveryTask_Call struct {
	*mock.Call
}

// SaveDeliveryTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task *entity.DeliveryTask
func (_e *MockDeliveryRepo_Expecter) SaveDeliveryTask(ctx interface{}, task interface{}) *MockDeliveryRepo_SaveDeliveryTask_Call {
	return &MockDeliveryRepo_SaveDeliveryTask_Call{Call: _e.mock.On("SaveDeliveryTask", ctx, task)}
}

func (_c *MockDeliveryRepo_SaveDeliveryTask_Call) Run(run func(ctx context.Context, task *entity.DeliveryTask)) *MockDeliveryRepo_SaveDeliveryTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.DeliveryTask
		if args[1] != nil {
			arg1 = args[1].(*entity.DeliveryTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_SaveDeliveryTask_Call) Return(err error) *MockDeliveryRepo_SaveDeliveryTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryRepo_SaveDeliveryTask_Call) RunAndReturn(run func(ctx context.Context, task *entity.DeliveryTask) error) *MockDeliveryRepo_SaveDeliveryTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeliveryStatus provides a mock function for the type MockDeliveryRepo
func (_mock *MockDeliveryRepo) UpdateDeliveryStatus(ctx context.Context, deliveryID string, status entity.DeliveryStatus, errorMessage *string) error {
	ret := _mock.Called(ctx, deliveryID, status, errorMessage)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeliveryStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, entity.DeliveryStatus, *string) error); ok {
		r0 = returnFunc(ctx, deliveryID, status, errorMessage)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryRepo_UpdateDeliveryStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeliveryStatus'
type MockDeliveryRepo_UpdateDeliveryStatus_Call struct {
	*mock.Call
}

// UpdateDeliveryStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryID string
//   - status entity.DeliveryStatus
//   - errorMessage *string
func (_e *MockDeliveryRepo_Expecter) UpdateDeliveryStatus(ctx interface{}, deliveryID interface{}, status interface{}, errorMessage interface{}) *MockDeliveryRepo_UpdateDeliveryStatus_Call {
	return &MockDeliveryRepo_UpdateDeliveryStatus_Call{Call: _e.mock.On("UpdateDeliveryStatus", ctx, deliveryID, status, errorMessage)}
}

func (_c *MockDeliveryRepo_UpdateDeliveryStatus_Call) Run(run func(ctx context.Context, deliveryID string, status entity.DeliveryStatus, errorMessage *string)) *MockDeliveryRepo_UpdateDeliveryStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 entity.DeliveryStatus
		if args[2] != nil {
			arg2 = args[2].(entity.DeliveryStatus)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeliveryRepo_UpdateDeliveryStatus_Call) Return(err error) *MockDeliveryRepo_UpdateDeliveryStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryRepo_UpdateDeliveryStatus_Call) RunAndReturn(run func(ctx context.Context, deliveryID string, status entity.DeliveryStatus, errorMessage *string) error) *MockDeliveryRepo_UpdateDeliveryStatus_Call {
	_c.Call.Return(run)
	return _c
}
