// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDeliveryHandler creates a new instance of MockDeliveryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryHandler {
	mock := &MockDeliveryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryHandler is an autogenerated mock type for the DeliveryHandler type
type MockDeliveryHandler struct {
	mock.Mock
}

type MockDeliveryHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryHandler) EXPECT() *MockDeliveryHandler_Expecter {
	return &MockDeliveryHandler_Expecter{mock: &_m.Mock}
}

// ExecuteDelivery provides a mock function for the type MockDeliveryHandler
func (_mock *MockDeliveryHandler) ExecuteDelivery(ctx context.Context, droneID string, orderID string, goodID string, parcelAutomatID string, arucoID int, coordinates string, weight float64, height float64, length float64, width float64, internalLockerCellID *string) error {
	ret := _mock.Called(ctx, droneID, orderID, goodID, parcelAutomatID, arucoID, coordinates, weight, height, length, width, internalLockerCellID)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteDelivery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int, string, float64, float64, float64, float64, *string) error); ok {
		r0 = returnFunc(ctx, droneID, orderID, goodID, parcelAutomatID, arucoID, coordinates, weight, height, length, width, internalLockerCellID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryHandler_ExecuteDelivery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteDelivery'
type MockDeliveryHandler_ExecuteDelivery_Call struct {
	*mock.Call
}

// ExecuteDelivery is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
//   - orderID string
//   - goodID string
//   - parcelAutomatID string
//   - arucoID int
//   - coordinates string
//   - weight float64
//   - height float64
//   - length float64
//   - width float64
//   - internalLockerCellID *string
func (_e *MockDeliveryHandler_Expecter) ExecuteDelivery(ctx interface{}, droneID interface{}, orderID interface{}, goodID interface{}, parcelAutomatID interface{}, arucoID interface{}, coordinates interface{}, weight interface{}, height interface{}, length interface{}, width interface{}, internalLockerCellID interface{}) *MockDeliveryHandler_ExecuteDelivery_Call {
	return &MockDeliveryHandler_ExecuteDelivery_Call{Call: _e.mock.On("ExecuteDelivery", ctx, droneID, orderID, goodID, parcelAutomatID, arucoID, coordinates, weight, height, length, width, internalLockerCellID)}
}

func (_c *MockDeliveryHandler_ExecuteDelivery_Call) Run(run func(ctx context.Context, droneID string, orderID string, goodID string, parcelAutomatID string, arucoID int, coordinates string, weight float64, height float64, length float64, width float64, internalLockerCellID *string)) *MockDeliveryHandler_ExecuteDelivery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 float64
		if args[7] != nil {
			arg7 = args[7].(float64)
		}
		var arg8 float64
		if args[8] != nil {
			arg8 = args[8].(float64)
		}
		var arg9 float64
		if args[9] != nil {
			arg9 = args[9].(float64)
		}
		var arg10 float64
		if args[10] != nil {
			arg10 = args[10].(float64)
		}
		var arg11 *string
		if args[11] != nil {
			arg11 = args[11].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
			arg8,
			arg9,
			arg10,
			arg11,
		)
	})
	return _c
}

func (_c *MockDeliveryHandler_ExecuteDelivery_Call) Return(err error) *MockDeliveryHandler_ExecuteDelivery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryHandler_ExecuteDelivery_Call) RunAndReturn(run func(ctx context.Context, droneID string, orderID string, goodID string, parcelAutomatID string, arucoID int, coordinates string, weight float64, height float64, length float64, width float64, internalLockerCellID *string) error) *MockDeliveryHandler_ExecuteDelivery_Call {
	_c.Call.Return(run)
	return _c
}

// HandleReturnTask provides a mock function for the type MockDeliveryHandler
func (_mock *MockDeliveryHandler) HandleReturnTask(ctx context.Context, droneID string, deliveryID string, baseMarkerID int) error {
	ret := _mock.Called(ctx, droneID, deliveryID, baseMarkerID)

	if len(ret) == 0 {
		panic("no return value specified for HandleReturnTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = returnFunc(ctx, droneID, deliveryID, baseMarkerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeliveryHandler_HandleReturnTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReturnTask'
type MockDeliveryHandler_HandleReturnTask_Call struct {
	*mock.Call
}

// HandleReturnTask is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
//   - deliveryID string
//   - baseMarkerID int
func (_e *MockDeliveryHandler_Expecter) HandleReturnTask(ctx interface{}, droneID interface{}, deliveryID interface{}, baseMarkerID interface{}) *MockDeliveryHandler_HandleReturnTask_Call {
	return &MockDeliveryHandler_HandleReturnTask_Call{Call: _e.mock.On("HandleReturnTask", ctx, droneID, deliveryID, baseMarkerID)}
}

func (_c *MockDeliveryHandler_HandleReturnTask_Call) Run(run func(ctx context.Context, droneID string, deliveryID string, baseMarkerID int)) *MockDeliveryHandler_HandleReturnTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeliveryHandler_HandleReturnTask_Call) Return(err error) *MockDeliveryHandler_HandleReturnTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeliveryHandler_HandleReturnTask_Call) RunAndReturn(run func(ctx context.Context, droneID string, deliveryID string, baseMarkerID int) error) *MockDeliveryHandler_HandleReturnTask_Call {
	_c.Call.Return(run)
	return _c
}
