// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDroneNotifier creates a new instance of MockDroneNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDroneNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDroneNotifier {
	mock := &MockDroneNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDroneNotifier is an autogenerated mock type for the DroneNotifier type
type MockDroneNotifier struct {
	mock.Mock
}

type MockDroneNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDroneNotifier) EXPECT() *MockDroneNotifier_Expecter {
	return &MockDroneNotifier_Expecter{mock: &_m.Mock}
}

// SendToDrone provides a mock function for the type MockDroneNotifier
func (_mock *MockDroneNotifier) SendToDrone(ctx context.Context, droneID string, message map[string]any) error {
	ret := _mock.Called(ctx, droneID, message)

	if len(ret) == 0 {
		panic("no return value specified for SendToDrone")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) error); ok {
		r0 = returnFunc(ctx, droneID, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDroneNotifier_SendToDrone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendToDrone'
type MockDroneNotifier_SendToDrone_Call struct {
	*mock.Call
}

// SendToDrone is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
//   - message map[string]any
func (_e *MockDroneNotifier_Expecter) SendToDrone(ctx interface{}, droneID interface{}, message interface{}) *MockDroneNotifier_SendToDrone_Call {
	return &MockDroneNotifier_SendToDrone_Call{Call: _e.mock.On("SendToDrone", ctx, droneID, message)}
}

func (_c *MockDroneNotifier_SendToDrone_Call) Run(run func(ctx context.Context, droneID string, message map[string]any)) *MockDroneNotifier_SendToDrone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDroneNotifier_SendToDrone_Call) Return(err error) *MockDroneNotifier_SendToDrone_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDroneNotifier_SendToDrone_Call) RunAndReturn(run func(ctx context.Context, droneID string, message map[string]any) error) *MockDroneNotifier_SendToDrone_Call {
	_c.Call.Return(run)
	return _c
}
