// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/skr1ms/SkyPostDelivery/drone-service/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDroneRepo creates a new instance of MockDroneRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDroneRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDroneRepo {
	mock := &MockDroneRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDroneRepo is an autogenerated mock type for the DroneRepo type
type MockDroneRepo struct {
	mock.Mock
}

type MockDroneRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDroneRepo) EXPECT() *MockDroneRepo_Expecter {
	return &MockDroneRepo_Expecter{mock: &_m.Mock}
}

// GetDroneIDByIP provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) GetDroneIDByIP(ctx context.Context, ipAddress string) (string, error) {
	ret := _mock.Called(ctx, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for GetDroneIDByIP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, ipAddress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, ipAddress)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_GetDroneIDByIP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDroneIDByIP'
type MockDroneRepo_GetDroneIDByIP_Call struct {
	*mock.Call
}

// GetDroneIDByIP is a helper method to define mock.On call
//   - ctx context.Context
//   - ipAddress string
func (_e *MockDroneRepo_Expecter) GetDroneIDByIP(ctx interface{}, ipAddress interface{}) *MockDroneRepo_GetDroneIDByIP_Call {
	return &MockDroneRepo_GetDroneIDByIP_Call{Call: _e.mock.On("GetDroneIDByIP", ctx, ipAddress)}
}

func (_c *MockDroneRepo_GetDroneIDByIP_Call) Run(run func(ctx context.Context, ipAddress string)) *MockDroneRepo_GetDroneIDByIP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDroneRepo_GetDroneIDByIP_Call) Return(s string, err error) *MockDroneRepo_GetDroneIDByIP_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockDroneRepo_GetDroneIDByIP_Call) RunAndReturn(run func(ctx context.Context, ipAddress string) (string, error)) *MockDroneRepo_GetDroneIDByIP_Call {
	_c.Call.Return(run)
	return _c
}

// GetDroneState provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) GetDroneState(ctx context.Context, droneID string) (*entity.DroneState, error) {
	ret := _mock.Called(ctx, droneID)

	if len(ret) == 0 {
		panic("no return value specified for GetDroneState")
	}

	var r0 *entity.DroneState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entity.DroneState, error)); ok {
		return returnFunc(ctx, droneID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entity.DroneState); ok {
		r0 = returnFunc(ctx, droneID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.DroneState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, droneID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDroneRepo_GetDroneState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDroneState'
type MockDroneRepo_GetDroneState_Call struct {
	*mock.Call
}

// GetDroneState is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
func (_e *MockDroneRepo_Expecter) GetDroneState(ctx interface{}, droneID interface{}) *MockDroneRepo_GetDroneState_Call {
	return &MockDroneRepo_GetDroneState_Call{Call: _e.mock.On("GetDroneState", ctx, droneID)}
}

func (_c *MockDroneRepo_GetDroneState_Call) Run(run func(ctx context.Context, droneID string)) *MockDroneRepo_GetDroneState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDroneRepo_GetDroneState_Call) Return(droneState *entity.DroneState, err error) *MockDroneRepo_GetDroneState_Call {
	_c.Call.Return(droneState, err)
	return _c
}

func (_c *MockDroneRepo_GetDroneState_Call) RunAndReturn(run func(ctx context.Context, droneID string) (*entity.DroneState, error)) *MockDroneRepo_GetDroneState_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDroneState provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) SaveDroneState(ctx context.Context, state *entity.DroneState) error {
	ret := _mock.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for SaveDroneState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.DroneState) error); ok {
		r0 = returnFunc(ctx, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDroneRepo_SaveDroneState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDroneState'
type MockDroneRepo_SaveDroneState_Call struct {
	*mock.Call
}

// SaveDroneState is a helper method to define mock.On call
//   - ctx context.Context
//   - state *entity.DroneState
func (_e *MockDroneRepo_Expecter) SaveDroneState(ctx interface{}, state interface{}) *MockDroneRepo_SaveDroneState_Call {
	return &MockDroneRepo_SaveDroneState_Call{Call: _e.mock.On("SaveDroneState", ctx, state)}
}

func (_c *MockDroneRepo_SaveDroneState_Call) Run(run func(ctx context.Context, state *entity.DroneState)) *MockDroneRepo_SaveDroneState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.DroneState
		if args[1] != nil {
			arg1 = args[1].(*entity.DroneState)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDroneRepo_SaveDroneState_Call) Return(err error) *MockDroneRepo_SaveDroneState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDroneRepo_SaveDroneState_Call) RunAndReturn(run func(ctx context.Context, state *entity.DroneState) error) *MockDroneRepo_SaveDroneState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDroneBattery provides a mock function for the type MockDroneRepo
func (_mock *MockDroneRepo) UpdateDroneBattery(ctx context.Context, droneID string, batteryLevel float64) error {
	ret := _mock.Called(ctx, droneID, batteryLevel)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDroneBattery")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = returnFunc(ctx, droneID, batteryLevel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDroneRepo_UpdateDroneBattery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDroneBattery'
type MockDroneRepo_UpdateDroneBattery_Call struct {
	*mock.Call
}

// UpdateDroneBattery is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
//   - batteryLevel float64
func (_e *MockDroneRepo_Expecter) UpdateDroneBattery(ctx interface{}, droneID interface{}, batteryLevel interface{}) *MockDroneRepo_UpdateDroneBattery_Call {
	return &MockDroneRepo_UpdateDroneBattery_Call{Call: _e.mock.On("UpdateDroneBattery", ctx, droneID, batteryLevel)}
}

func (_c *MockDroneRepo_UpdateDroneBattery_Call) Run(run func(ctx context.Context, droneID string, batteryLevel float64)) *MockDroneRepo_UpdateDroneBattery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDroneRepo_UpdateDroneBattery_Call) Return(err error) *MockDroneRepo_UpdateDroneBattery_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDroneRepo_UpdateDroneBattery_Call) RunAndReturn(run func(ctx context.Context, droneID string, batteryLevel float64) error) *MockDroneRepo_UpdateDroneBattery_Call {
	_c.Call.Return(run)
	return _c
}
