// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockVideoHandler creates a new instance of MockVideoHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoHandler {
	mock := &MockVideoHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVideoHandler is an autogenerated mock type for the VideoHandler type
type MockVideoHandler struct {
	mock.Mock
}

type MockVideoHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoHandler) EXPECT() *MockVideoHandler_Expecter {
	return &MockVideoHandler_Expecter{mock: &_m.Mock}
}

// HandleVideoFrame provides a mock function for the type MockVideoHandler
func (_mock *MockVideoHandler) HandleVideoFrame(ctx context.Context, droneID string, frameData []byte, deliveryID string) error {
	ret := _mock.Called(ctx, droneID, frameData, deliveryID)

	if len(ret) == 0 {
		panic("no return value specified for HandleVideoFrame")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte, string) error); ok {
		r0 = returnFunc(ctx, droneID, frameData, deliveryID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVideoHandler_HandleVideoFrame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleVideoFrame'
type MockVideoHandler_HandleVideoFrame_Call struct {
	*mock.Call
}

// HandleVideoFrame is a helper method to define mock.On call
//   - ctx context.Context
//   - droneID string
//   - frameData []byte
//   - deliveryID string
func (_e *MockVideoHandler_Expecter) HandleVideoFrame(ctx interface{}, droneID interface{}, frameData interface{}, deliveryID interface{}) *MockVideoHandler_HandleVideoFrame_Call {
	return &MockVideoHandler_HandleVideoFrame_Call{Call: _e.mock.On("HandleVideoFrame", ctx, droneID, frameData, deliveryID)}
}

func (_c *MockVideoHandler_HandleVideoFrame_Call) Run(run func(ctx context.Context, droneID string, frameData []byte, deliveryID string)) *MockVideoHandler_HandleVideoFrame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockVideoHandler_HandleVideoFrame_Call) Return(err error) *MockVideoHandler_HandleVideoFrame_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVideoHandler_HandleVideoFrame_Call) RunAndReturn(run func(ctx context.Context, droneID string, frameData []byte, deliveryID string) error) *MockVideoHandler_HandleVideoFrame_Call {
	_c.Call.Return(run)
	return _c
}
